import { describe,it,expect } from 'vitest';
import { randomUUID } from 'node:crypto';
import { advance,createCorp,createWorld,facilityMap,landCost,preview,R,snapshot,MAX } from '../src/engine.js';
import { executeAction } from '../src/actions.js';
import { Game,Corp,Facility } from '../src/types.js';
import { rules } from '../../../packages/rules/src/index.js';

const NOW=Date.parse('2026-10-09T12:00:00Z');
function fixture(){const world=createWorld(NOW);world.regions[0]!.modifiers={soil:1,oil:1,minerals:1,industry:1,solar:1};const c=createCorp(randomUUID(),'Test Corporation',NOW,world);return {world,corps:[c]} as Game;}
function build(game:Game,id:string,count=1){const c=game.corps[0]!,r=game.world.regions[0]!;executeAction(game,c,{type:'facility.build',regionId:r.id,facilityId:id,quantity:count},c.lastProcessed);return c.holdings[r.id]!.facilities.at(-1)!;}
function seedFacility(game:Game,c:Corp,type:string,regionId=game.world.regions[0]!.id){const d=facilityMap.get(type)!;const f:Facility={id:randomUUID(),type,level:0,xp:0,nextCycle:NOW+d.cycleSeconds*1000,enabled:true,plus:true,allowPlus:false,installed:[],costPaid:d.cost,materialsPaid:{...d.materials},builtAt:NOW};c.holdings[regionId]!.facilities.push(f);return f;}

describe('authoritative chronological economy',()=>{
 it('unboosted starter builds a documented tree farm and produces exactly at the deadline',()=>{const g=fixture(),c=g.corps[0]!,h=c.holdings.verdant!;const f=build(g,'tree_farm');expect(c.cash).toBe(rules.starterCash-facilityMap.get('tree_farm')!.cost);advance(g,f.nextCycle-1);expect(h.inventory.wood||0).toBe(0);advance(g,f.nextCycle);expect(h.inventory.wood).toBe(2);expect(h.inventory.wood_plus||0).toBe(0);});
 it('does not conjure downstream resources without inputs',()=>{const g=fixture(),c=g.corps[0]!,h=c.holdings.verdant!;const f=seedFacility(g,c,'steel_mill');advance(g,NOW+600000);expect(h.inventory.steel||0).toBe(0);expect(f.xp).toBe(0);expect(snapshot(g,c,NOW+600000).holdings.verdant.facilities[0].status).toBe('starved');});
 it('one catch-up equals one-second reference advancement with shared scarce inputs and chains',()=>{const g=fixture(),c=g.corps[0]!;for(const type of ['oil_well','oil_refinery','gas_station','oil_refinery'])seedFacility(g,c,type);const stepped=structuredClone(g);advance(g,NOW+4*3600000);for(let t=NOW+1000;t<=NOW+4*3600000;t+=1000)advance(stepped,t);expect(g.corps[0]!.holdings).toEqual(stepped.corps[0]!.holdings);expect(g.corps[0]!.cash).toEqual(stepped.corps[0]!.cash);expect(g.corps[0]!.rng).toEqual(stepped.corps[0]!.rng);});
 it('matches reference through voter-boon expiry and regional modifier boundaries',()=>{const g=fixture(),c=g.corps[0]!;c.rewards.vote=NOW-rules.vote.boonSeconds*1000+4000;const f=seedFacility(g,c,'oil_well');f.nextCycle=NOW+1000;const a=structuredClone(g),b=structuredClone(g);advance(a,NOW+2*3600000);for(let t=NOW+1000;t<=NOW+2*3600000;t+=1000)advance(b,t);expect(a.corps[0]!.holdings).toEqual(b.corps[0]!.holdings);expect(a.corps[0]!.rng).toBe(b.corps[0]!.rng);});
 it('preserves random state on restart and never rerolls a completed research outcome',()=>{const g=fixture(),c=g.corps[0]!,h=c.holdings.verdant!;seedFacility(g,c,'research_facility');c.cash=rules.research.cash;h.inventory.energy=rules.research.energy;executeAction(g,c,{type:'research.start',regionId:'verdant'},NOW);const before=structuredClone(h.research[0]!.outcome),restart=JSON.parse(JSON.stringify(g));advance(restart,NOW+rules.research.maximumSeconds*1000);executeAction(restart,restart.corps[0],{type:'research.claim',regionId:'verdant',id:h.research[0]!.id},NOW+rules.research.maximumSeconds*1000);expect(restart.corps[0].holdings.verdant.research[0].rewards).toEqual(before);expect(()=>executeAction(restart,restart.corps[0],{type:'research.claim',id:h.research[0]!.id},NOW+rules.research.maximumSeconds*1000)).toThrow('already claimed');});
 it('scrap gives units, explicit addxp gives levels, plus-input preference never consumes plus while disabled',()=>{const g=fixture(),c=g.corps[0]!,h=c.holdings.verdant!;const f=seedFacility(g,c,'oil_refinery');h.inventory.clothing=100000;executeAction(g,c,{type:'inventory.scrap',assetId:'clothing',quantity:100000},NOW);expect(h.inventory.scrap).toBe(100000);expect(f.level).toBe(0);executeAction(g,c,{type:'facility.addxp',id:f.id,quantity:100000},NOW);expect(f.level).toBe(1);h.inventory.crude_oil_plus=100;advance(g,f.nextCycle);expect(h.inventory.crude_oil_plus).toBe(100);executeAction(g,c,{type:'facility.plus',id:f.id,enabled:true},c.lastProcessed);advance(g,f.nextCycle);expect(h.inventory.crude_oil_plus).toBeLessThan(100);});
 it('land tokens do not raise the paid-land exponent and liquidation refunds historical values',()=>{const g=fixture(),c=g.corps[0]!,h=c.holdings.verdant!;const before=landCost(h,1,c,g.world.regions[0]!);c.tokens=1;executeAction(g,c,{type:'upgrade.buy',upgradeId:'land'},NOW);expect(h.land).toBe(14);expect(landCost(h,1,c,g.world.regions[0]!)).toBe(before);c.cash=10000000;executeAction(g,c,{type:'land.buy',quantity:2},NOW);const f=build(g,'tree_farm');expect(h.purchasedLand).toBe(2);const p=preview(c,g.world,'verdant','liquidation',NOW);expect(p.refund).toBe(Math.floor((h.landSpent+f.costPaid)*rules.liquidationRefund));});
 it('partial global order fill conserves escrow and fees, cancellation returns only remaining amount',()=>{const g=fixture(),seller=g.corps[0]!,buyer=createCorp(randomUUID(),'Buyer',NOW,g.world);g.corps.push(buyer);seedFacility(g,seller,'logistics_center');seedFacility(g,buyer,'logistics_center','ironridge');seller.holdings.verdant!.inventory.wood=100;buyer.cash=100000;const initial=seller.cash+buyer.cash;executeAction(g,seller,{type:'order.create',assetId:'wood',quantity:100,price:20,side:'sell'},NOW);executeAction(g,buyer,{type:'order.create',regionId:'ironridge',assetId:'wood',quantity:40,price:25,side:'buy'},NOW+1);const order=g.world.orders[0]!;expect(order.remaining).toBe(60);expect(buyer.inbox![0]!.quantity).toBe(40);expect(buyer.holdings.ironridge!.inventory.wood||0).toBe(0);executeAction(g,buyer,{type:'logistics.claim',id:buyer.inbox![0]!.id},NOW+2);executeAction(g,seller,{type:'order.cancel',id:order.id},NOW+3);executeAction(g,seller,{type:'logistics.claim',all:true},NOW+3);expect(seller.holdings.verdant!.inventory.wood).toBe(60);expect(buyer.holdings.ironridge!.inventory.wood).toBe(40);expect(seller.cash+buyer.cash).toBe(initial-Math.floor(40*20*R.marketFee));expect(()=>executeAction(g,seller,{type:'order.cancel',id:order.id},NOW+3)).toThrow('closed');});
 it('exports consume documented gasoline and cannot claim twice or change region inventory early',()=>{const g=fixture(),c=g.corps[0]!,h=c.holdings.verdant!;seedFacility(g,c,'logistics_center');seedFacility(g,c,'logistics_center','suncoast');h.inventory.truck=1;h.inventory.wood=100;h.inventory.gasoline=100;executeAction(g,c,{type:'export.dispatch',toRegionId:'suncoast',assetId:'wood',quantity:100},NOW);const s=c.shipments[0]!;expect(s.arrivesAt).toBe(NOW+rules.export.normalSeconds*1000);expect(()=>executeAction(g,c,{type:'export.claim',id:s.id},NOW)).toThrow('not arrived');advance(g,s.arrivesAt);executeAction(g,c,{type:'export.claim',id:s.id},s.arrivesAt);expect(c.holdings.suncoast!.inventory.wood).toBe(100);expect(h.inventory.truck).toBe(1);expect(()=>executeAction(g,c,{type:'export.claim',id:s.id},s.arrivesAt)).toThrow('already claimed');});
 it('guards integer ranges, account-local facility ownership and reward replay',()=>{const g=fixture(),c=g.corps[0]!;expect(()=>executeAction(g,c,{type:'land.buy',quantity:0.5},NOW)).toThrow('whole number');expect(()=>executeAction(g,c,{type:'facility.toggle',id:randomUUID()},NOW)).toThrow('not found');expect(()=>executeAction(g,c,{type:'reward.vote'},NOW)).toThrow('one minute');executeAction(g,c,{type:'reward.vote'},NOW+60000);expect(()=>executeAction(g,c,{type:'reward.vote'},NOW+60001)).toThrow('cooldown');});
 it('stalls saturated cash and inventory producers before consuming inputs without blocking another corporation',()=>{const g=fixture(),c=g.corps[0]!,h=c.holdings.verdant!;const farm=seedFacility(g,c,'tree_farm'),station=seedFacility(g,c,'gas_station');h.inventory.wood=MAX;h.inventory.gasoline=100;c.cash=MAX;const other=createCorp(randomUUID(),'Unsaturated',NOW,g.world);g.corps.push(other);seedFacility(g,other,'tree_farm');advance(g,NOW+60000);expect(h.inventory.wood).toBe(MAX);expect(h.inventory.gasoline).toBe(100);expect(c.cash).toBe(MAX);expect(other.holdings.verdant!.inventory.wood).toBeGreaterThan(0);const state=snapshot(g,c,NOW+60000);expect(state.holdings.verdant.facilities.find((f:any)=>f.id===farm.id).status).toBe('capacity');expect(state.holdings.verdant.facilities.find((f:any)=>f.id===station.id).capacityReason).toContain('Cash capacity');executeAction(g,c,{type:'land.buy',quantity:1},NOW+60000);executeAction(g,c,{type:'npc.sell',assetId:'wood',quantity:1},NOW+60000);expect(h.inventory.wood).toBe(MAX-1);expect(()=>advance(g,NOW+120000)).not.toThrow();});
 it('continues retail safely with saturated historical counters and rejects nonfinite simulation clocks',()=>{const g=fixture(),c=g.corps[0]!,h=c.holdings.verdant!;seedFacility(g,c,'hq');seedFacility(g,c,'retail_store');seedFacility(g,c,'customer_support_center');h.inventory.car=100;const max=Number.MAX_SAFE_INTEGER;c.stats.earned=max;c.season.xp=max;c.season.challenges[`${Math.floor(NOW/86400000)}:salesCents`]=max;executeAction(g,c,{type:'retail.configure',assetId:'car',price:1000000},NOW);h.retail[0]!.revenue=max;const before=c.cash;advance(g,h.retail[0]!.nextSale);expect(c.cash).toBeGreaterThan(before);expect(c.stats.earned).toBe(max);expect(c.season.xp).toBe(max);expect(h.retail[0]!.revenue).toBe(max);expect(()=>advance(g,NaN)).toThrow('finite');expect(()=>advance(g,Infinity)).toThrow('finite');expect(()=>advance(g,-1)).toThrow('finite');});
 it('liquidation settles escrow and deliveries once, returns inbound cargo, and leaves other-region research intact',()=>{const g=fixture(),c=g.corps[0]!,h=c.holdings.verdant!,other=c.holdings.ironridge!;seedFacility(g,c,'logistics_center');seedFacility(g,c,'logistics_center','ironridge');c.cash=100000000;Object.assign(h.inventory,{wood:100,truck:1,gasoline:1000});Object.assign(other.inventory,{wood:50,truck:1,gasoline:1000});executeAction(g,c,{type:'order.create',side:'sell',assetId:'wood',quantity:20,price:100},NOW);executeAction(g,c,{type:'order.create',side:'buy',assetId:'coal',quantity:10,price:30},NOW);executeAction(g,c,{type:'export.dispatch',assetId:'wood',quantity:25,toRegionId:'ironridge'},NOW);executeAction(g,c,{type:'export.dispatch',regionId:'ironridge',assetId:'wood',quantity:15,toRegionId:'verdant'},NOW);h.research=[{id:'local',status:'working',readyAt:NOW+3600000,outcome:[]}];other.research=[{id:'remote',status:'working',readyAt:NOW+3600000,outcome:[]}];c.inbox=[{id:'goods',assetId:'wood',quantity:5,regionId:'verdant',status:'pending'},{id:'cash',assetId:'cash',quantity:999,regionId:'verdant',status:'pending'}];const before=c.cash,p=preview(c,g.world,'verdant','liquidation',NOW);executeAction(g,c,{type:'liquidation.reset'},NOW);expect(c.cash).toBe(before+300+p.refund);expect(g.world.orders.every(o=>o.status==='cancelled')).toBe(true);expect(c.shipments).toHaveLength(0);expect(other.inventory.wood).toBe(50);expect(other.inventory.truck).toBe(1);expect(other.research[0]!.id).toBe('remote');expect(c.holdings.verdant!.research).toHaveLength(0);expect(c.inbox![0]!.status).toBe('liquidated');expect(c.inbox![1]!.status).toBe('pending');executeAction(g,c,{type:'logistics.claim',id:'cash'},NOW);expect(c.cash).toBe(before+300+p.refund+999);expect(()=>executeAction(g,c,{type:'research.claim',id:'local'},NOW)).toThrow('not found');expect(()=>executeAction(g,c,{type:'order.cancel',id:g.world.orders[0]!.id},NOW)).toThrow('closed');const repeat=c.cash;executeAction(g,c,{type:'liquidation.reset'},NOW);expect(c.cash).toBe(repeat);});
 it('prestige closes pending escrow without overflowing temporary ledgers and never resurrects projects or deliveries',()=>{const g=fixture(),c=g.corps[0]!,h=c.holdings.verdant!;seedFacility(g,c,'logistics_center');h.inventory.wood=100;c.cash=1000000;executeAction(g,c,{type:'order.create',side:'buy',assetId:'coal',quantity:10,price:30},NOW);executeAction(g,c,{type:'order.create',side:'sell',assetId:'wood',quantity:100,price:100},NOW);c.cash=MAX;h.inventory.wood=MAX;h.research=[{id:'working',status:'working',readyAt:NOW+1000,outcome:[{assetId:'rocket',quantity:1}]}];c.inbox=[{id:'pending',assetId:'wood',quantity:5,regionId:'verdant',status:'pending'}];const p=preview(c,g.world,'verdant','prestige',NOW);expect(p.eligible).toBe(true);executeAction(g,c,{type:'prestige.reset'},NOW);expect(c.cash).toBe(rules.starterCash);expect(c.tokens).toBe(p.tokens);expect(c.score).toBe(p.score);expect(g.world.orders.every(o=>o.status==='cancelled')).toBe(true);expect(c.inbox).toHaveLength(0);expect(c.holdings.verdant!.research).toHaveLength(0);advance(g,NOW+10000);expect(c.holdings.verdant!.inventory.rocket||0).toBe(0);expect(()=>executeAction(g,c,{type:'order.cancel',id:g.world.orders[0]!.id},NOW+10000)).toThrow('closed');});
});
