import { randomUUID } from 'node:crypto';
import { describe, expect, it } from 'vitest';
import { executeAction } from '../src/actions.js';
import { advance, createCorp, createWorld, cycleMs, facilityMap, marketPrice, MAX, netWorth, preview, R, snapshot } from '../src/engine.js';
import { projectBonus } from '../src/expansion.js';
import { captureReturnBaseline, makeReturnSummary, normalizeEnhancements, notifyCorporation, recordInsights } from '../src/insights.js';
import { Corp, Dict, Facility, Game } from '../src/types.js';
import { enhancementRules, expansionRules } from '../../../packages/rules/src/expansion.js';

const NOW=Date.parse('2026-10-09T12:00:00Z');
function fixture(enabled=true){const world=createWorld(NOW),corps=[createCorp(randomUUID(),'Buyer',NOW,world),createCorp(randomUUID(),'Supplier',NOW,world)];world.expansionEnabled=enabled;world.regions[0]!.modifiers={soil:1,oil:1,minerals:1,industry:1,solar:1};for(const c of corps)c.cash=100000000;const g:Game={world,corps};normalizeEnhancements(g);return g;}
function act(g:Game,c:Corp,type:string,args:Dict={},now=NOW){return executeAction(g,c,{type,...args},now);}
function seed(g:Game,c:Corp,type:string,regionId='verdant'){const d=facilityMap.get(type)!;const f:Facility={id:randomUUID(),type,level:0,xp:0,nextCycle:NOW+d.cycleSeconds*1000,enabled:true,plus:false,allowPlus:false,installed:[],costPaid:d.cost,materialsPaid:{...d.materials},builtAt:NOW};c.holdings[regionId]!.facilities.push(f);return f;}
function logistics(g:Game){for(const c of g.corps)seed(g,c,'logistics_center');}
function cashTotal(g:Game){return g.corps.reduce((n,c)=>n+c.cash+(c.commitments?.cash||0)+(c.inbox||[]).filter(i=>i.status==='pending'&&i.assetId==='cash').reduce((m,i)=>m+i.quantity,0),0);}
function goodsTotal(g:Game,id:string){return g.corps.reduce((n,c)=>n+Object.values(c.holdings).reduce((m,h)=>m+(h.inventory[id]||0),0)+(c.commitments?.assets[id]||0)+(c.inbox||[]).filter(i=>i.status==='pending'&&i.assetId===id).reduce((m,i)=>m+i.quantity,0),0);}
function contract(g:Game,quantity=100,price=101){logistics(g);act(g,g.corps[0]!,'contract.create',{assetId:'wood',quantity,price,deadlineSeconds:3600});return g.world.contracts!.at(-1)!;}
function project(g:Game,id='industry_grant'){act(g,g.corps[0]!,'project.create',{projectTypeId:id});return g.world.projects!.at(-1)!;}
function fund(g:Game,p:Dict,c=g.corps[0]!,now=NOW){Object.assign(c.holdings[p.regionId]!.inventory,p.requirements.materials);act(g,c,'project.contribute',{id:p.id,regionId:p.regionId,cash:p.requirements.cash,materials:p.requirements.materials},now);}

describe('facility organization and real production insights',()=>{
 it('persists groups, favorites and goals and validates every owned facility before changing any',()=>{const g=fixture(),c=g.corps[0]!,a=seed(g,c,'tree_farm'),b=seed(g,c,'oil_well'),foreign=seed(g,g.corps[1]!,'tree_farm');act(g,c,'facility.organize',{ids:[a.id,b.id],group:' Raw inputs ',favorite:true});act(g,c,'goal.pin',{facilityId:'steel_mill',quantity:3});expect(snapshot(g,c,NOW).holdings.verdant.groups).toEqual(['Raw inputs']);expect(c.pinnedGoals!.verdant!.quantity).toBe(3);expect(()=>act(g,c,'facility.batch',{ids:[a.id,foreign.id],enabled:false})).toThrow('not found');expect(a.enabled).toBe(true);act(g,c,'facility.batch',{ids:[a.id,b.id],enabled:false});advance(g,NOW+60000);expect(a.metrics).toBeUndefined();act(g,c,'facility.batch',{ids:[a.id,b.id],enabled:true},NOW+60000);expect(a.nextCycle).toBe(NOW+60000+cycleMs(a,c,g.world.regions[0]!));const restored=JSON.parse(JSON.stringify(g)) as Game;expect(restored.corps[0]!.holdings.verdant!.facilities[0]!.favorite).toBe(true);act(g,c,'goal.clear');expect(c.pinnedGoals!.verdant).toBeUndefined();});
 it('counts successful, starved and capacity cycles without inventing realized profit',()=>{const g=fixture(),c=g.corps[0]!,h=c.holdings.verdant!,farm=seed(g,c,'tree_farm'),mill=seed(g,c,'steel_mill');captureReturnBaseline(c,NOW);advance(g,NOW+60000);expect(farm.metrics!.successfulCycles).toBeGreaterThan(0);expect(mill.metrics!.starvedCycles).toBeGreaterThan(0);const metrics=snapshot(g,c,NOW+60000).holdings.verdant.facilities.find((f:Dict)=>f.id===farm.id).metrics;expect(metrics.utilization).toBe(1);expect(metrics.inputCostPerMinute).toBe(0);expect(metrics.estimatedMarginPerMinute).toBeGreaterThan(0);expect(metrics.note).toContain('not realized profit');h.inventory.wood=MAX;advance(g,NOW+120000);expect(farm.metrics!.capacityCycles).toBeGreaterThan(0);const summary=makeReturnSummary(g,c,NOW+120000);expect(summary.baselineAvailable).toBe(true);expect(summary.cyclesCompleted).toBe(farm.metrics!.successfulCycles);expect(summary.starvedCycles).toBe(mill.metrics!.starvedCycles);expect(summary.capacityCycles).toBe(farm.metrics!.capacityCycles);expect(summary.elapsedMs).toBe(120000);});
 it('samples observed balances and watched prices with bounded retention and no fabricated offline backfill',()=>{const g=fixture(),c=g.corps[0]!;act(g,c,'market.watch',{assetId:'wood',enabled:true});recordInsights(g,NOW);recordInsights(g,NOW+1000);expect(c.insights!.corporation).toHaveLength(1);expect(Object.values(c.insights!.prices).every((p:any)=>p.length===1)).toBe(true);c.cash-=100;recordInsights(g,NOW+86400000);expect(c.insights!.corporation).toHaveLength(2);expect(c.insights!.corporation[1].cash).toBe(c.cash);expect(c.insights!.prices['verdant:wood'][1].sell).toBe(marketPrice(g.world.regions[0]!,'wood','sell',NOW+86400000));c.insights!.forceSample=true;recordInsights(g,NOW+86400001);expect(c.insights!.corporation).toHaveLength(3);for(let i=0;i<enhancementRules.corporationHistoryPoints+1;i++)recordInsights(g,NOW+2*86400000+i*60000);expect(c.insights!.corporation).toHaveLength(enhancementRules.corporationHistoryPoints);act(g,c,'market.watch',{assetId:'wood',enabled:false});recordInsights(g,NOW+4*86400000);expect(c.insights!.prices).toEqual({});});
 it('quotes executable price-time fills and fees and emits private readable notifications',()=>{const g=fixture(),buyer=g.corps[0]!,seller=g.corps[1]!;logistics(g);seller.holdings.verdant!.inventory.wood=20;act(g,buyer,'order.create',{assetId:'wood',quantity:5,price:103,side:'buy'});const quote=act(g,seller,'order.quote',{assetId:'wood',quantity:10,price:100,side:'sell'}).quote;expect(quote.subtotal).toBe(1000);expect(quote.fee).toBe(Math.floor(1000*R.marketFee));expect(quote.estimatedMatchedQuantity).toBe(5);expect(quote.estimatedExecutionTotal).toBe(515);expect(quote.estimatedExecutionNet).toBe(515-Math.floor(515*R.marketFee));act(g,seller,'order.create',{assetId:'wood',quantity:10,price:100,side:'sell'});expect(buyer.notificationsList!.some(n=>n.type==='order_fill')).toBe(true);expect(seller.notificationsList!.some(n=>n.type==='order_fill')).toBe(true);const n=seller.notificationsList![0]!;act(g,seller,'notification.read',{ids:[n.id]});expect(n.read).toBe(true);expect(buyer.notificationsList![0]!.read).toBe(false);expect(()=>act(g,seller,'order.quote',{assetId:'blueprint_oil_mapping',quantity:1,price:1,side:'buy'})).toThrow('cannot be traded');for(let i=0;i<enhancementRules.maximumNotifications+1;i++)notifyCorporation(seller,'test','test','test',NOW);expect(seller.notificationsList).toHaveLength(enhancementRules.maximumNotifications);});
});

describe('optional supply contract escrow',()=>{
 it('defaults off without changing core balances and refuses new expansion commitments',()=>{const g=fixture(false),c=g.corps[0]!,before=c.cash;logistics(g);expect(createWorld(NOW).expansionEnabled).toBe(false);expect(()=>act(g,c,'contract.create',{assetId:'wood',quantity:1,price:1})).toThrow('disabled');expect(()=>act(g,c,'project.create',{projectTypeId:'community_garden'})).toThrow('disabled');expect(c.cash).toBe(before);});
 it('conserves money and goods through partial delivery, cancellation, claiming and serialization',()=>{const g=fixture(),buyer=g.corps[0]!,seller=g.corps[1]!;seller.holdings.verdant!.inventory.wood=100;const cash=cashTotal(g),goods=goodsTotal(g,'wood'),x=contract(g);const worth=netWorth(buyer);expect(buyer.commitments!.cash).toBe(10100);act(g,seller,'contract.accept',{id:x.id});act(g,seller,'contract.deliver',{id:x.id,quantity:40});expect(x.escrowCash).toBe(6060);expect(x.delivered).toBe(40);expect(cashTotal(g)).toBe(cash);expect(goodsTotal(g,'wood')).toBe(goods);act(g,seller,'contract.cancel',{id:x.id});expect(x.refundedCash).toBe(6060);expect(buyer.commitments!.cash).toBe(0);act(g,buyer,'contract.claim',{id:x.id});act(g,seller,'contract.claim',{id:x.id});expect(cashTotal(g)).toBe(cash);expect(goodsTotal(g,'wood')).toBe(goods);expect(buyer.holdings.verdant!.inventory.wood).toBe(40);expect(netWorth(buyer)).toBe(worth-4040+40*15);expect(()=>act(g,seller,'contract.claim',{id:x.id})).toThrow('No matching');const restored=JSON.parse(JSON.stringify(g)) as Game;advance(restored,NOW+7200000);expect(cashTotal(restored)).toBe(cash);expect(restored.world.contracts![0]!.status).toBe('cancelled');});
 it('enforces party ownership, exclusive acceptance, escrow limits and asset restrictions',()=>{const g=fixture(),x=contract(g),third=createCorp(randomUUID(),'Third',NOW,g.world);g.corps.push(third);seed(g,third,'logistics_center');act(g,g.corps[1]!,'contract.accept',{id:x.id});expect(()=>act(g,third,'contract.accept',{id:x.id})).toThrow('no longer open');expect(()=>act(g,third,'contract.deliver',{id:x.id,quantity:1})).toThrow('not found');expect(()=>act(g,third,'contract.cancel',{id:x.id})).toThrow('not found');expect(()=>act(g,g.corps[0]!,'contract.create',{assetId:'wood',quantity:MAX,price:MAX})).toThrow('safe integer');expect(()=>act(g,g.corps[0]!,'contract.create',{assetId:'blueprint_oil_mapping',quantity:1,price:1})).toThrow('cannot be offered');});
 it('disabling expansion permits already accepted deliveries, refunds and claims, but blocks new acceptance',()=>{const g=fixture(),x=contract(g),seller=g.corps[1]!;seller.holdings.verdant!.inventory.wood=100;act(g,seller,'contract.accept',{id:x.id});g.world.expansionEnabled=false;act(g,seller,'contract.deliver',{id:x.id,quantity:100});expect(x.status).toBe('completed');act(g,seller,'contract.claim',{id:x.id});act(g,g.corps[0]!,'contract.claim',{id:x.id});g.world.expansionEnabled=true;const y=contract(g);g.world.expansionEnabled=false;expect(()=>act(g,seller,'contract.accept',{id:y.id})).toThrow('disabled');act(g,g.corps[0]!,'contract.cancel',{id:y.id});act(g,g.corps[0]!,'contract.claim',{id:y.id});});
 it('expires once at the saved deadline and queues refunds even when buyer cash is at capacity',()=>{const g=fixture(),x=contract(g),buyer=g.corps[0]!;buyer.cash=MAX;advance(g,x.deadline-1);expect(x.status).toBe('open');advance(g,x.deadline);expect(x.status).toBe('expired');expect(buyer.cash).toBe(MAX);expect(buyer.inbox!.filter(i=>i.relatedId===x.id)).toHaveLength(1);advance(g,x.deadline+86400000);expect(buyer.inbox!.filter(i=>i.relatedId===x.id)).toHaveLength(1);buyer.cash-=10100;act(g,buyer,'contract.claim',{id:x.id},x.deadline+86400000);expect(buyer.cash).toBe(MAX);});
});

describe('pooled regional project accounting and effects',()=>{
 it('removes only the happiness bonus actually applied at the regional cap',()=>{const g=fixture(),r=g.world.regions[0]!,p=project(g,'community_garden');r.happiness=99;fund(g,p);expect(r.happiness).toBe(100);expect(r.projectHappiness).toBe(1);p.benefitExpiresAt=NOW+10000;r.projectBenefits[0].expiresAt=p.benefitExpiresAt;advance(g,p.benefitExpiresAt);expect(r.happiness).toBe(99);expect(r.projectHappiness).toBe(0);});
 it('conserves both corporations contributions on withdrawal and cancellation with refunds claimable without logistics',()=>{const g=fixture(),a=g.corps[0]!,b=g.corps[1]!,p=project(g);a.holdings.verdant!.inventory.wood=2000;b.holdings.verdant!.inventory.steel=500;const cash=cashTotal(g),wood=goodsTotal(g,'wood'),steel=goodsTotal(g,'steel'),worth=netWorth(a);act(g,a,'project.contribute',{id:p.id,cash:100000,materials:{wood:2000}});act(g,b,'project.contribute',{id:p.id,cash:200000,materials:{steel:500}});expect(netWorth(a)).toBe(worth);expect(cashTotal(g)).toBe(cash);expect(goodsTotal(g,'wood')).toBe(wood);expect(goodsTotal(g,'steel')).toBe(steel);act(g,a,'project.withdraw',{id:p.id});act(g,a,'project.claim',{id:p.id});expect(p.contributors).toHaveLength(1);act(g,a,'project.cancel',{id:p.id});act(g,b,'project.claim',{id:p.id});expect(cashTotal(g)).toBe(cash);expect(goodsTotal(g,'wood')).toBe(wood);expect(goodsTotal(g,'steel')).toBe(steel);expect(()=>act(g,b,'project.claim',{id:p.id})).toThrow('No matching');});
 it('completes only after exact requirements, consumes actual contributions, and applies a capped expiring region benefit',()=>{const g=fixture(),c=g.corps[0]!,r=g.world.regions[0]!,p=project(g),farm=seed(g,c,'tree_farm');Object.assign(c.holdings.verdant!.inventory,p.requirements.materials);const cash=cashTotal(g),wood=goodsTotal(g,'wood'),before=cycleMs(farm,c,r);act(g,c,'project.contribute',{id:p.id,cash:p.requirements.cash,materials:{wood:9999,steel:5000}});expect(p.status).toBe('funding');act(g,c,'project.contribute',{id:p.id,materials:{wood:1}});expect(p.status).toBe('completed');expect(cashTotal(g)).toBe(cash-p.requirements.cash);expect(goodsTotal(g,'wood')).toBe(wood-p.requirements.materials.wood);expect(c.commitments!.cash).toBe(0);expect(cycleMs(farm,c,r)).toBe(Math.round(before/1.05));expect(()=>act(g,c,'project.withdraw',{id:p.id})).toThrow('cannot be withdrawn');expect(()=>project(g)).toThrow('already active');r.projectBenefits.push({effect:{productionSpeed:1},expiresAt:p.benefitExpiresAt});expect(projectBonus(r,'productionSpeed',NOW)).toBe(expansionRules.projects.maximumProductionBonus);advance(g,p.benefitExpiresAt);expect(projectBonus(r,'productionSpeed',p.benefitExpiresAt)).toBe(0);});
 it('expiry refunds all contributors exactly once after disabling and saturation cannot stop catch-up',()=>{const g=fixture(),a=g.corps[0]!,b=g.corps[1]!,p=project(g,'community_garden');a.holdings.verdant!.inventory.wood=100;b.holdings.verdant!.inventory.cotton=50;act(g,a,'project.contribute',{id:p.id,cash:100,materials:{wood:100}});act(g,b,'project.contribute',{id:p.id,cash:200,materials:{cotton:50}});a.cash=MAX;a.holdings.verdant!.inventory.wood=MAX;const total=cashTotal(g);g.world.expansionEnabled=false;advance(g,p.deadline);expect(p.status).toBe('expired');expect(p.contributors).toHaveLength(0);expect(cashTotal(g)).toBe(total);expect(a.inbox!.filter(i=>i.relatedId===p.id)).toHaveLength(2);advance(g,p.deadline+1);expect(a.inbox!.filter(i=>i.relatedId===p.id)).toHaveLength(2);});
 it('rejects irrelevant/prototype material keys, zero and excess contributions before commitment',()=>{const g=fixture(),c=g.corps[0]!,p=project(g);expect(()=>act(g,c,'project.contribute',{id:p.id})).toThrow('positive contribution');expect(()=>act(g,c,'project.contribute',{id:p.id,cash:p.requirements.cash+1})).toThrow('whole number');expect(()=>act(g,c,'project.contribute',{id:p.id,materials:{constructor:1}})).toThrow('not required');expect(()=>act(g,c,'project.contribute',{id:p.id,materials:{coal:1}})).toThrow('not required');expect(c.commitments!.cash).toBe(0);});
 it('fast catch-up matches stepped simulation through production-benefit expiry without retroactive rewards',()=>{const g=fixture(),c=g.corps[0]!,p=project(g);seed(g,c,'tree_farm');advance(g,NOW+30000);fund(g,p,c,NOW+30000);p.benefitExpiresAt=NOW+90000;g.world.regions[0]!.projectBenefits[0].expiresAt=NOW+90000;const fast=structuredClone(g),slow=structuredClone(g);advance(fast,NOW+180000);for(let t=NOW+31000;t<=NOW+180000;t+=1000)advance(slow,t);expect(fast.corps[0]!.holdings).toEqual(slow.corps[0]!.holdings);expect(fast.corps[0]!.cash).toBe(slow.corps[0]!.cash);expect(fast.world.regions).toEqual(slow.world.regions);expect(fast.corps[0]!.rng).toBe(slow.corps[0]!.rng);});
 it('happiness is removed at expiry and a freight project only shortens newly dispatched shipment duration',()=>{const g=fixture(),c=g.corps[0]!,r=g.world.regions[0]!,garden=project(g,'community_garden');fund(g,garden);expect(r.happiness).toBe(53);garden.benefitExpiresAt=NOW+10000;r.projectBenefits[0].expiresAt=NOW+10000;advance(g,NOW+10000);expect(r.happiness).toBe(50);const freight=project(g,'transport_hub');fund(g,freight,c,NOW+10000);seed(g,c,'logistics_center');seed(g,c,'logistics_center','ironridge');Object.assign(c.holdings.verdant!.inventory,{wood:10,gasoline:1000,truck:1});act(g,c,'export.dispatch',{assetId:'wood',quantity:10,toRegionId:'ironridge'},NOW+10000);expect(c.shipments[0]!.arrivesAt-c.shipments[0]!.dispatchedAt).toBe(R.exportSeconds*1000*.9);});
});

describe('reset conservation across expansion commitments',()=>{
 it('liquidation returns unspent buyer escrow and sells withdrawn local project material exactly once',()=>{const g=fixture(),buyer=g.corps[0]!,seller=g.corps[1]!,x=contract(g);seller.holdings.verdant!.inventory.wood=100;act(g,seller,'contract.accept',{id:x.id});act(g,seller,'contract.deliver',{id:x.id,quantity:40});const p=project(g);buyer.holdings.verdant!.inventory.steel=100;act(g,buyer,'project.contribute',{id:p.id,cash:10000,materials:{steel:100}});const before=buyer.cash,pv=preview(buyer,g.world,'verdant','liquidation',NOW);expect(pv.expansion.cancelledContracts).toBe(1);expect(pv.expansion.withdrawnProjects).toBe(1);expect(pv.expansion.refundableCash).toBe(6060+10000);act(g,buyer,'liquidation.reset');expect(buyer.cash).toBe(before+pv.refund);expect(x.status).toBe('cancelled');expect(p.contributors).toHaveLength(0);expect(seller.inbox!.filter(i=>i.status==='pending'&&i.assetId==='cash')[0]!.quantity).toBe(4040);act(g,buyer,'contract.claim',{id:x.id});act(g,buyer,'project.claim',{id:p.id});expect(buyer.cash).toBe(before+pv.refund+6060+10000);const after=buyer.cash;act(g,buyer,'liquidation.reset');expect(buyer.cash).toBe(after);});
 it('supplier prestige refunds buyer undelivered funds, preserves other contributors and erases only the resetting corporation payout',()=>{const g=fixture(),buyer=g.corps[0]!,seller=g.corps[1]!,x=contract(g);seller.holdings.verdant!.inventory.wood=100;act(g,seller,'contract.accept',{id:x.id});act(g,seller,'contract.deliver',{id:x.id,quantity:40});const p=project(g);buyer.holdings.verdant!.inventory.steel=100;seller.holdings.verdant!.inventory.wood=100;act(g,buyer,'project.contribute',{id:p.id,cash:1000,materials:{steel:100}});act(g,seller,'project.contribute',{id:p.id,cash:2000,materials:{wood:100}});seller.cash=MAX;act(g,seller,'prestige.reset');expect(x.status).toBe('cancelled');expect(x.escrowCash).toBe(0);expect(seller.commitments!.cash).toBe(0);expect(seller.inbox).toHaveLength(0);expect(p.contributors.map((x:Dict)=>x.corporationId)).toEqual([buyer.id]);expect(p.contributed.materials.steel).toBe(100);expect(p.contributed.materials.wood).toBe(0);act(g,buyer,'contract.claim',{id:x.id});expect(buyer.holdings.verdant!.inventory.wood).toBe(40);const cash=buyer.cash;advance(g,NOW+7200000);expect(buyer.cash).toBe(cash);expect(buyer.inbox!.filter(i=>i.relatedId===x.id)).toHaveLength(2);});
});
