import { describe,expect,it } from 'vitest';
import { createCorp,createWorld,facilityMap,advance,MAX,snapshot } from '../apps/server/src/engine.js';
import { executeAction } from '../apps/server/src/actions.js';
import { productionTarget,validateTarget } from '../apps/server/src/production-targets.js';
import { facilityFlow,flowTotals,resourceBalances } from '../apps/server/src/resource-balances.js';
import type { Corp,Dict,Facility,Game } from '../apps/server/src/types.js';

const NOW=Date.parse('2026-10-09T12:00:00Z');
function fixture(){const world=createWorld(NOW);world.regions[0]!.modifiers={soil:1,oil:1,minerals:1,industry:1,solar:1};const c=createCorp('owner','Owner',NOW,world),other=createCorp('other','Other',NOW,world);c.cash=1_000_000_000;return {world,corps:[c,other]} as Game;}
function seed(g:Game,type:string,extra:Partial<Facility>={},c=g.corps[0]!){const d=facilityMap.get(type)!,h=c.holdings.verdant!,f:Facility={id:`${type}:${h.facilities.length}`,type,level:0,xp:0,nextCycle:NOW+d.cycleSeconds*1000,enabled:true,plus:false,allowPlus:false,installed:[],builtAt:NOW,costPaid:d.cost,materialsPaid:{...d.materials},...extra};h.facilities.push(f);return f;}
function target(g:Game,assetId:string,amount:number,extra:Dict={}){return productionTarget(g,g.corps[0]!,{regionId:'verdant',assetId,mode:'rate',amount,source:'produce',...extra},NOW);}
function act(g:Game,c:Corp,type:string,args:Dict={}){return executeAction(g,c,{type,regionId:'verdant',...args},NOW);}

describe('production target planning',()=>{
 it('expands a whole-factory chain without changing inventory, capital, RNG or timers',()=>{const g=fixture(),before=structuredClone(g),plan=target(g,'steel',5);expect(g).toEqual(before);expect(plan.status).toBe('planned');expect(plan.facilities.find(f=>f.facilityId==='steel_mill')!.additionalCount).toBe(3);expect(plan.facilities.some(f=>f.facilityId==='iron_mine')).toBe(true);expect(plan.facilities.some(f=>f.facilityId==='coal_mine')).toBe(true);expect(plan.projected.sustainableNetPerMinute).toBeGreaterThanOrEqual(5);expect(plan.requirements.land.required).toBe(plan.facilities.reduce((n,f)=>n+f.land,0));expect(plan.requirements.cash.construction).toBe(plan.facilities.reduce((n,f)=>n+f.buildCost,0));});
 it('uses existing capacity and resumes only the paused factories needed before proposing additions',()=>{const g=fixture(),c=g.corps[0]!,r=g.world.regions[0]!,f=seed(g,'tree_farm');seed(g,'tree_farm',{enabled:false});seed(g,'tree_farm',{enabled:false});const perMinute=facilityFlow(f,c,r).outputs.wood!,plan=target(g,'wood',perMinute*2);const farm=plan.facilities.find(f=>f.facilityId==='tree_farm')!;expect(farm.existingCount).toBe(3);expect(farm.activeCount).toBe(1);expect(farm.resumeCount).toBe(1);expect(farm.additionalCount).toBe(0);expect(plan.current.sustainableNetPerMinute).toBe(perMinute);expect(plan.projected.sustainableNetPerMinute).toBe(perMinute*2);expect(c.holdings.verdant!.facilities.filter(f=>f.enabled)).toHaveLength(1);});
 it('reserves existing consumers once when planning a net surplus of their shared input',()=>{const g=fixture(),c=g.corps[0]!,r=g.world.regions[0]!,tree=seed(g,'tree_farm'),factory=seed(g,'furniture_factory');const wood=facilityFlow(tree,c,r).outputs.wood!,consumption=facilityFlow(factory,c,r).inputs.wood!,goal=wood*2,plan=target(g,'wood',goal);const farm=plan.facilities.find(f=>f.facilityId==='tree_farm')!;expect(farm.additionalCount).toBe(Math.ceil((goal+consumption-wood)/wood));expect(plan.projected.capacityInputPerMinute).toBe(consumption);expect(plan.projected.sustainableNetPerMinute).toBeGreaterThanOrEqual(goal);});
 it('merges upstream demand shared by several recipes into one producer group',()=>{const g=fixture(),plan=target(g,'car',.1);const oils=plan.facilities.filter(f=>f.facilityId==='oil_well');expect(oils).toHaveLength(1);const oil=oils[0]!,required=plan.facilities.reduce((n,f)=>n+(f.inputsPerMinute.crude_oil||0),0),per=oil.outputsPerMinute.crude_oil!/oil.additionalCount;expect(oil.additionalCount).toBe(Math.ceil((required-1e-8)/per));expect(plan.projected.sustainableNetPerMinute).toBeGreaterThanOrEqual(.1-1e-8);});
 it('distinguishes nominal output from sustainable throughput without finite upstream supply',()=>{const g=fixture();seed(g,'steel_mill');const plan=target(g,'steel',1);expect(plan.current.capacityOutputPerMinute).toBeGreaterThan(1);expect(plan.current.sustainableOutputPerMinute).toBe(0);expect(plan.facilities.find(f=>f.facilityId==='steel_mill')!.additionalCount).toBe(0);expect(plan.facilities.some(f=>f.facilityId==='iron_mine'&&f.additionalCount>0)).toBe(true);expect(plan.projected.sustainableNetPerMinute).toBeGreaterThanOrEqual(1);});
 it('supports upstream buying without proposing that upstream factory and reports shared purchase limits',()=>{const g=fixture(),plan=target(g,'furniture',5,{choices:{wood:'buy'}});expect(plan.facilities.some(f=>f.facilityId==='tree_farm')).toBe(false);expect(plan.purchases.find(p=>p.assetId==='wood')!.perMinute).toBeGreaterThan(0);expect(plan.purchases[0]!.npcAvailable).toBe(true);expect(plan.blockers.some(b=>b.code==='manual_purchase')).toBe(true);expect(plan.projected.sustainableNetPerMinute).toBeGreaterThanOrEqual(5);const large=target(g,'car',2,{choices:{steel:'buy',rubber:'buy',cpu:'buy',plastic:'buy',glass:'buy',gasoline_engine:'buy'}});expect(large.purchases.reduce((n,p)=>n+p.affordableQuantity*p.unitPrice,0)).toBeLessThanOrEqual(large.purchases[0]!.allowanceRemaining);});
 it('a buy target accounts for unsupplied existing producers instead of assuming their nameplate output',()=>{const g=fixture();seed(g,'steel_mill');const p=target(g,'steel',2,{source:'buy'});expect(p.purchases.find(x=>x.assetId==='steel')!.perMinute).toBe(2);expect(p.facilities.every(f=>f.additionalCount===0)).toBe(true);expect(p.projected.sustainableNetPerMinute).toBe(2);});
 it('budgets construction and recurring purchases against the same capital once',()=>{const g=fixture(),initial=target(g,'furniture',5,{choices:{wood:'buy'}}),construction=initial.requirements.cash.total,purchase=initial.purchases[0]!;expect(construction).toBeGreaterThan(0);expect(purchase.total).toBeGreaterThan(0);g.corps[0]!.cash=Math.max(construction,purchase.total);const plan=target(g,'furniture',5,{choices:{wood:'buy'}});expect(plan.requirements.cash.missing).toBe(0);expect(plan.requirements.cash.availableForPurchases).toBe(g.corps[0]!.cash-construction);expect(plan.purchases[0]!.affordableQuantity).toBeLessThan(purchase.quantity);expect(plan.purchases.reduce((n,p)=>n+p.affordableQuantity*p.unitPrice,0)+construction).toBeLessThanOrEqual(g.corps[0]!.cash);expect(plan.blockers.some(b=>b.code==='purchase_budget')).toBe(true);});
 it('stock goals use existing stock, conservative current net ETA and an explicit future planning horizon',()=>{const g=fixture(),c=g.corps[0]!;seed(g,'tree_farm');c.holdings.verdant!.inventory.wood=100;const ready=target(g,'wood',100,{mode:'stock'});expect(ready.status).toBe('ready');expect(ready.eta).toMatchObject({status:'ready',seconds:0});const pending=target(g,'wood',200,{mode:'stock',horizonMinutes:10});expect(pending.target.requiredNetPerMinute).toBe(10);expect(pending.eta.status).toBe('estimate');expect(pending.eta.seconds).toBeGreaterThan(0);const stalled=fixture();seed(stalled,'furniture_factory');stalled.corps[0]!.holdings.verdant!.inventory.wood=1000;expect(target(stalled,'furniture',10,{mode:'stock'}).eta.status).toBe('blocked');});
 it('reports zero quality capacity honestly and uses current technologies/levels and vault effects',()=>{const g=fixture();expect(target(g,'wood_plus',1).status).toBe('blocked');const f=seed(g,'tree_farm',{plus:true,level:50,xp:5000000});let plan=target(g,'wood_plus',1);expect(plan.current.capacityOutputPerMinute).toBeGreaterThan(1);expect(plan.warnings.some(w=>w.includes('statistical expectation'))).toBe(true);g.corps[0]!.space.vault.relic_of_efficiency=1;plan=target(g,'wood_plus',1);expect(plan.current.capacityOutputPerMinute).toBe(0);expect(plan.status).toBe('blocked');expect(f.level).toBe(50);});
 it('honors an alternate producer and enforces finite bounds without overflowing a large plan',()=>{const g=fixture(),p=target(g,'energy',1,{producerChoices:{energy:'solar_power_plant'}});expect(p.facilities.some(f=>f.facilityId==='solar_power_plant')).toBe(true);expect(p.facilities.some(f=>f.facilityId==='coal_power_plant')).toBe(false);expect(target(g,'wood',1000000).status).toBe('blocked');expect(()=>target(g,'wood',Infinity)).toThrow('positive rate');expect(()=>target(g,'wood',NaN)).toThrow('positive rate');expect(()=>target(g,'wood',0)).toThrow('positive rate');expect(()=>target(g,'wood',1.5,{mode:'stock'})).toThrow('whole stock');expect(()=>target(g,'wood',1,{horizonMinutes:10081})).toThrow('horizon');expect(()=>target(g,'wood',1,{producerChoices:{wood:'steel_mill'}})).toThrow('corresponding');});
 it('bounds cyclic recipe traversal rather than hanging or inventing supply',()=>{const d=facilityMap.get('tree_farm')!,before=d.inputs;try{d.inputs={wood:2};const g=fixture(),plan=target(g,'wood',1);expect(plan.status).toBe('blocked');expect(plan.blockers.some(b=>['dependency_cycle','facility_limit','unsustainable'].includes(b.code))).toBe(true);}finally{d.inputs=before;}});
});

describe('recorded resource balances and private saved plans',()=>{
 it('includes the first cycle in a complete elapsed observation interval without doubling the next rate',()=>{const g=fixture(),c=g.corps[0]!,r=g.world.regions[0]!,f=seed(g,'tree_farm'),first=f.nextCycle;advance(g,first);const firstBalance=resourceBalances(c,r).find(b=>b.assetId==='wood')!,firstOutput=firstBalance.actual!.output;expect(firstBalance.actual!.observedSince).toBe(NOW);expect(firstBalance.actual!.outputPerMinute).toBeCloseTo(firstOutput*60000/(first-NOW));const second=f.nextCycle;advance(g,second);const secondBalance=resourceBalances(c,r).find(b=>b.assetId==='wood')!;expect(secondBalance.actual!.output).toBe(firstOutput*2);expect(secondBalance.actual!.outputPerMinute).toBeCloseTo(firstOutput*2*60000/(second-NOW));const flow=facilityFlow(f,c,r),view=snapshot(g,c,second).holdings.verdant.facilities[0];expect(view.expectedInputRates).toEqual(flow.inputs);expect(view.expectedOutputRates).toEqual(flow.outputs);});
 it('starts actual observations without fabricating history and measures actual quality units separately',()=>{const g=fixture(),c=g.corps[0]!,r=g.world.regions[0]!;c.rng=102938;seed(g,'tree_farm',{plus:true,level:50,xp:5000000});expect(resourceBalances(c,r).find(b=>b.assetId==='wood')!.actual).toBeNull();advance(g,NOW+60000);const balances=resourceBalances(c,r),normal=balances.find(b=>b.assetId==='wood')!,plus=balances.find(b=>b.assetId==='wood_plus')!;expect(normal.actual!.output).toBe(c.holdings.verdant!.inventory.wood||0);expect(plus.actual!.output).toBe(c.holdings.verdant!.inventory.wood_plus||0);expect(normal.actual!.outputPerMinute).toBe(normal.actual!.output);expect(plus.actual!.outputPerMinute).toBe(plus.actual!.output);expect(normal.actual!.observedSince).toBe(NOW);expect(normal.actual!.observedUntil).toBe(NOW+60000);const recorded=normal.actual!.output;c.holdings.verdant!.inventory.wood=MAX;expect(resourceBalances(c,r).find(b=>b.assetId==='wood')!.actual!.output).toBe(recorded);expect(snapshot(g,c,NOW+60000).holdings.verdant.resourceBalances).toHaveLength(balances.length);});
 it('does not reserve one resource output twice across competing consumers',()=>{const g=fixture(),c=g.corps[0]!,r=g.world.regions[0]!,raw=seed(g,'tree_farm'),consumers=Array.from({length:20},()=>seed(g,'furniture_factory')),flows=[raw,...consumers].map(f=>facilityFlow(f,c,r)),t=flowTotals(flows);expect(t.sustainableInput.wood).toBeLessThanOrEqual(t.sustainableOutput.wood!+1e-8);const balance=resourceBalances(c,r).find(x=>x.assetId==='wood')!;expect(balance.producers[0]!.count).toBe(1);expect(balance.consumers[0]!.count).toBe(20);expect(balance.capacityNetPerMinute).toBeLessThan(0);expect(balance.depletionSeconds).toBe(0);});
 it('validates, persists and updates named targets without exposing or overwriting another corporation plan',()=>{const g=fixture(),c=g.corps[0]!,other=g.corps[1]!,payload={name:' Steel expansion ',assetId:'steel',mode:'rate',amount:3,source:'produce',choices:{coal:'buy'}};const first=act(g,c,'plan.save',payload).savedPlan;expect(first.name).toBe('Steel expansion');expect(snapshot(g,c,NOW).savedPlans).toHaveLength(1);expect(snapshot(g,other,NOW).savedPlans).toHaveLength(0);expect(()=>act(g,other,'plan.save',{...payload,id:first.id})).toThrow('not found');expect(()=>act(g,other,'plan.delete',{id:first.id})).toThrow('not found');const updated=act(g,c,'plan.save',{...payload,id:first.id,name:'Revised steel',amount:6}).savedPlan;expect(updated.id).toBe(first.id);expect(c.savedPlans).toHaveLength(1);const loaded=JSON.parse(JSON.stringify(g));expect(loaded.corps[0].savedPlans[0].choices.coal).toBe('buy');act(g,c,'plan.delete',{id:first.id});expect(c.savedPlans).toHaveLength(0);expect(()=>act(g,c,'plan.delete',{id:first.id})).toThrow('not found');});
 it('rejects malformed sources, excessive saved plans and inaccessible regions without economic effects',()=>{const g=fixture(),c=g.corps[0]!,before=c.cash,payload={name:'Plan',assetId:'wood',mode:'rate',amount:1,source:'produce'};expect(()=>validateTarget(g,c,{...payload,regionId:'missing'})).toThrow('valid region');expect(()=>act(g,c,'plan.save',{...payload,choices:{wood:'invent'}})).toThrow('produce or buy');expect(()=>act(g,c,'plan.save',{...payload,name:' '.repeat(10)})).toThrow('names');for(let i=0;i<20;i++)act(g,c,'plan.save',{...payload,name:'Plan '+i});expect(()=>act(g,c,'plan.save',payload)).toThrow('at most 20');expect(c.cash).toBe(before);});
});

