import { randomUUID } from 'node:crypto';
import { policies, services, rules, levelFromXp, exportFuel } from '../../../packages/rules/src/index.js';
import { Corp, Dict, Game, GameError, Holding, Order } from './types.js';
import { enhancementRules } from '../../../packages/rules/src/expansion.js';
import { normalizeEnhancements, notifyCorporation, quoteOrder } from './insights.js';
import { claimExpansionInbox, expansionAction, projectBonus, resetExpansion } from './expansion.js';
import { savePlan, deletePlan } from './production-targets.js';
import { R, add, assetMap, assetPrice, bounded, consume, cycleMs, emptyHolding, facilityMap, getAsset, getHolding, has, integer, landCost, marketPrice, note, preview, requireFacility, roll, spend, stock, techMap, xp, installedTech, regionalEffect, serviceActive, buildCost, buyingLimit, challengeProgress, constructionWorth } from './engine.js';

function text(v:any,label:string,max=100){if(typeof v!=='string'||!v.trim()||v.trim().length>max)throw new GameError(`${label} must contain 1–${max} characters.`);return v.trim();}
function facility(h:Holding,id:any){const f=h.facilities.find(f=>f.id===id);if(!f)throw new GameError('Facility not found in this region.',404);return f;}
function selectedFacilities(h:Holding,ids:any){if(!Array.isArray(ids)||!ids.length||ids.length>enhancementRules.maximumBatchFacilities||ids.some(id=>typeof id!=='string'))throw new GameError('Choose between 1 and 2,000 facilities in this region.');return [...new Set(ids)].map(id=>facility(h,id));}
function globalHas(c:Corp,...types:string[]){return Object.values(c.holdings).some(h=>has(h,...types));}
function economics(c:Corp,h:Holding,resources:Dict,multiplier=1){for(const[id,n]of Object.entries(resources)){if(id==='cash')spend(c,Number(n)*multiplier);else consume(h,id,Number(n)*multiplier);}}
function cancelOrder(game:Game,o:Order){if(o.status!=='open')throw new GameError('This order is already closed.');const owner=game.corps.find(c=>c.id===o.corporationId)!;if(o.side==='buy')add(owner,'cash',bounded(o.remaining*o.price));else stock(owner.holdings[o.regionId]!,o.assetId,o.remaining);o.status='cancelled';}
export function matchOrder(game:Game,order:Order,now:number){
 const matches=game.world.orders.filter(o=>o.id!==order.id&&o.status==='open'&&o.corporationId!==order.corporationId&&o.assetId===order.assetId&&o.side!==order.side&&(order.side==='buy'?o.price<=order.price:o.price>=order.price))
 .sort((a,b)=>(order.side==='buy'?a.price-b.price:b.price-a.price)||a.createdAt-b.createdAt||a.id.localeCompare(b.id));
 for(const maker of matches){if(!order.remaining)break;const amount=Math.min(order.remaining,maker.remaining),price=maker.price,total=bounded(amount*price);
  const buy=order.side==='buy'?order:maker,sell=order.side==='sell'?order:maker;
  const buyer=game.corps.find(c=>c.id===buy.corporationId)!,seller=game.corps.find(c=>c.id===sell.corporationId)!;
  const fee=Math.floor(total*R.marketFee);seller.inbox||=[];seller.inbox.push({id:randomUUID(),regionId:sell.regionId,assetId:'cash',quantity:total-fee,from:buyer.name,status:'pending',createdAt:now});add(buyer,'cash',bounded((buy.price-price)*amount));buyer.inbox||=[];buyer.inbox.push({id:randomUUID(),regionId:buy.regionId,assetId:buy.assetId,quantity:amount,from:seller.name,status:'pending',createdAt:now});challengeProgress(seller,'salesCents',total,now);challengeProgress(buyer,'purchasesCents',total,now);
  seller.stats.sold+=amount;seller.stats.earned=Math.min(Number.MAX_SAFE_INTEGER,seller.stats.earned+total-fee);xp(seller,1);xp(buyer,1);
  maker.remaining-=amount;order.remaining-=amount;if(!maker.remaining)maker.status='filled';if(!order.remaining)order.status='filled';
  game.world.trades.push({id:randomUUID(),regionId:order.regionId,assetId:order.assetId,quantity:amount,price,fee,buyerId:buyer.id,sellerId:seller.id,at:now});
  note(buyer,`Purchased ${amount} ${order.assetId} from ${seller.name}.`,now,'trade');note(seller,`Sold ${amount} ${order.assetId} to ${buyer.name}.`,now,'trade');
  notifyCorporation(buyer,'order_fill',buy.remaining?'Buy order partially filled':'Buy order filled',`${amount} ${getAsset(order.assetId).name} purchased for ${total} cents; claim the goods in Logistics.`,now,buy.id);
  notifyCorporation(seller,'order_fill',sell.remaining?'Sell order partially filled':'Sell order filled',`${amount} ${getAsset(order.assetId).name} sold; ${total-fee} cents after the ${fee}-cent fee are ready to claim.`,now,sell.id);
 }
 game.world.trades=game.world.trades.slice(-500);
}
function researchOutcome(c:Corp,count:number){const results:Dict[]=[];for(let i=0;i<count;i++){const value=roll(c);let cumulative=0,rarity='superior';for(const [id,chance]of Object.entries(rules.research.rarities)){cumulative+=chance;if(value<cumulative){rarity=id;break;}}const pool=(rules.research.rewards as Dict)[rarity] as Dict[];const chosen=pool[Math.floor(roll(c)*pool.length)]!;results.push({[chosen.kind==='blueprint'?'technologyId':'assetId']:chosen.id,rarity,quantity:1});}return results;}

export function executeAction(game:Game,c:Corp,a:Dict,now:number):Dict {
 normalizeEnhancements(game);
 const type=text(a.type,'Action',60);const rid=typeof a.regionId==='string'?a.regionId:game.world.regions[0]!.id;const h=getHolding(c,rid,game.world),r=game.world.regions.find(r=>r.id===rid)!;h.blueprints||={};for(const [id,q]of Object.entries(h.blueprints))if(h.inventory['blueprint_'+id]===undefined)h.inventory['blueprint_'+id]=q;
 const result:Dict={};
 if(expansionAction(game,c,a,now))return result;
 switch(type){
 case 'plan.save':{result.savedPlan=savePlan(game,c,a,now);break;}
 case 'plan.delete':{deletePlan(c,a.id);break;}
 case 'facility.organize':{const fs=selectedFacilities(h,a.ids);if(a.group===undefined&&a.favorite===undefined)throw new GameError('Choose a group or favorite preference.');if(a.group!==undefined&&(typeof a.group!=='string'||a.group.trim().length>enhancementRules.maximumGroupNameLength))throw new GameError('Group names must be at most 40 characters.');if(a.favorite!==undefined&&typeof a.favorite!=='boolean')throw new GameError('Favorite must be a boolean.');const next=a.group===undefined?undefined:a.group.trim(),ids=new Set(fs.map(f=>f.id)),groups=new Set(h.facilities.map(f=>next!==undefined&&ids.has(f.id)?next:f.group).filter(Boolean));if(groups.size>enhancementRules.maximumGroupsPerRegion)throw new GameError('A region supports at most 30 named facility groups.');for(const f of fs){if(next!==undefined)f.group=next;if(a.favorite!==undefined)f.favorite=a.favorite;}break;}
 case 'facility.batch':{const fs=selectedFacilities(h,a.ids);if(typeof a.enabled!=='boolean')throw new GameError('Choose whether the selected facilities should run.');for(const f of fs){if(f.enabled===a.enabled)continue;f.enabled=a.enabled;if(f.enabled)f.nextCycle=now+cycleMs(f,c,r);}note(c,`${a.enabled?'Resumed':'Paused'} ${fs.length} selected facilities.`,now,'production');break;}
 case 'goal.pin':{if(!facilityMap.has(a.facilityId))throw new GameError('Choose a known facility goal.');const quantity=integer(a.quantity??1,'Goal quantity',1,100),baselineCount=h.facilities.filter(f=>f.type===a.facilityId).length;c.pinnedGoals![rid]={facilityId:a.facilityId,quantity,createdAt:now,baselineCount,targetCount:baselineCount+quantity};break;}
 case 'goal.clear':{delete c.pinnedGoals![rid];break;}
 case 'market.watch':{getAsset(a.assetId);if(typeof a.enabled!=='boolean')throw new GameError('Choose whether to watch this asset.');if(a.enabled){if(!c.watchlist!.includes(a.assetId)){if(c.watchlist!.length>=enhancementRules.maximumWatchedAssets)throw new GameError('Your watchlist supports at most 24 assets.');c.watchlist!.push(a.assetId);}}else c.watchlist=c.watchlist!.filter(id=>id!==a.assetId);break;}
 case 'notification.read':{if(a.all!==true&&(!Array.isArray(a.ids)||a.ids.length>enhancementRules.maximumNotifications||a.ids.some((id:any)=>typeof id!=='string')))throw new GameError('Select notification IDs or mark all read.');for(const n of c.notificationsList!)if(a.all===true||a.ids.includes(n.id))n.read=true;break;}
 case 'order.quote':{result.quote=quoteOrder(game,c,a,now);break;}
 case 'land.buy':{const q=integer(a.quantity,'Land quantity',1,1000),cost=landCost(h,q,c,r);spend(c,cost);h.purchasedLand=(h.purchasedLand??Math.max(0,h.land-10))+Math.max(0,q-Math.max(0,10-h.land));h.land=bounded(h.land+q);h.landSpent=bounded(h.landSpent+cost);note(c,`Purchased ${q} land in ${r.name}.`,now);break;}
 case 'facility.build':{const d=facilityMap.get(a.facilityId);if(!d)throw new GameError('Unknown facility.');const q=integer(a.quantity??1,'Facility quantity',1,100);
  if(h.facilities.length+q>2000)throw new GameError('This region supports at most 2,000 facilities per corporation.');
  const used=h.facilities.reduce((n,f)=>n+Number(facilityMap.get(f.type)?.land||1),0);if(used+Number(d.land||1)*q>h.land)throw new GameError('Purchase more land before construction.');
  for(const requirement of d.requires||[]){const required=requirement.replace(/^global:/,'');if(!(requirement.startsWith('global:')?globalHas(c,required):has(h,required))&&!c.technologies.includes(required))throw new GameError(`Requires ${facilityMap.get(required)?.name||required}.`);}
  if(d.id==='research_facility'&&h.facilities.filter(f=>f.type===d.id).length+q>rules.research.maxFacilities)throw new GameError('Research facilities are limited to eight per region.');
  if(['retail_store','customer_support_center'].includes(d.id)&&!globalHas(c,'hq','headquarters'))throw new GameError('Build a headquarters in any region first.');
  if(d.id==='airport'&&!globalHas(c,'air_traffic_control'))throw new GameError('Build air traffic control in any region first.');
  const cost=buildCost(d,r);spend(c,bounded(cost*q));economics(c,h,d.materials||{},q);
  for(let i=0;i<q;i++){const f={id:randomUUID(),type:d.id,level:0,xp:0,nextCycle:now+Number(d.cycleSeconds||60)*1000,enabled:true,plus:true,allowPlus:false,installed:[],costPaid:cost,materialsPaid:{...d.materials},builtAt:now};f.nextCycle=now+cycleMs(f,c,r);h.facilities.push(f);}
  c.stats.built+=q;challengeProgress(c,'builds',q,now);xp(c,q*10);note(c,`Built ${q} ${d.name}.`,now);break;}
 case 'facility.demolish':{const f=facility(h,a.id);if(f.installed.length)throw new GameError('Uninstall technologies before demolition.');add(c,'cash',Math.floor(constructionWorth(f)*rules.liquidationRefund));h.facilities=h.facilities.filter(x=>x.id!==f.id);if(f.type==='retail_store'&&!has(h,'retail_store'))h.retail=[];note(c,`Demolished ${facilityMap.get(f.type)?.name}; refunded 40% of historical construction value.`,now);break;}
 case 'facility.addxp':{const f=facility(h,a.id),q=integer(a.quantity,'Scrap quantity');if(f.xp+q>rules.facilityXpPerLevel*rules.maxFacilityLevel)throw new GameError('This would exceed the facility level cap.');consume(h,'scrap',q);f.xp+=q;f.level=levelFromXp(f.xp);break;}
 case 'facility.toggle':{const f=facility(h,a.id);f.enabled=!f.enabled;if(f.enabled)f.nextCycle=now+cycleMs(f,c,r);break;}
 case 'facility.plus':{const f=facility(h,a.id);if(typeof a.enabled!=='boolean')throw new GameError('Choose whether plus inputs are allowed.');f.allowPlus=a.enabled;if(typeof a.producePlus==='boolean')f.plus=a.producePlus;break;}
 case 'inventory.lock':{getAsset(a.assetId);h.locks=h.locks.includes(a.assetId)?h.locks.filter(x=>x!==a.assetId):[...h.locks,a.assetId];break;}
 case 'inventory.scrap':{const asset=getAsset(a.assetId);if(!asset.scrappable)throw new GameError('This asset cannot be scrapped.');const q=integer(a.quantity),amount=q*(asset.quality?2:1);consume(h,a.assetId,q);stock(h,'scrap',amount);h.scrap=bounded(h.scrap+amount);c.stats.scrapped+=q;note(c,`Converted ${q} ${a.assetId} to ${amount} scrap. Use scrap to add facility XP.`,now);break;}
 case 'npc.buy':case 'npc.sell':{const asset=getAsset(a.assetId),q=integer(a.quantity),side=type==='npc.buy'?'buy':'sell';
  if(side==='buy'?asset.npcBuy===false:asset.npcSell===false)throw new GameError(`This asset cannot be ${side==='buy'?'bought from':'sold to'} the NPC market.`);
  const price=marketPrice(r,asset.id,side,now),total=bounded(price*q),day=Math.floor(now/3600000);if(h.purchaseDay!==day){h.purchaseDay=day;h.npcPurchases={};}
  if(side==='buy'){const limit=buyingLimit(c,h,r,now);if((h.npcPurchases.spent||0)+total>limit)throw new GameError('This purchase exceeds your regional hourly NPC buy limit. Build logistics centers or wait for the next hour.');spend(c,total);stock(h,asset.id,q);h.npcPurchases.spent=(h.npcPurchases.spent||0)+total;}
  else{consume(h,asset.id,q);add(c,'cash',total);c.stats.sold+=q;c.stats.earned=Math.min(Number.MAX_SAFE_INTEGER,c.stats.earned+total);xp(c,Math.min(100,Math.floor(total/10000)));}challengeProgress(c,side==='buy'?'purchasesCents':'salesCents',total,now);
  note(c,`${side==='buy'?'Bought':'Sold'} ${q} ${asset.name} on the NPC market.`,now,'trade');break;}
 case 'order.create':{requireFacility(h,['logistics_center','logistics_centre'],'Build a logistics center in this region to trade player orders.');const asset=getAsset(a.assetId),q=integer(a.quantity),price=integer(a.price,'Unit price');if(!['buy','sell'].includes(a.side))throw new GameError('Order side must be buy or sell.');
  if(asset.tradeable===false)throw new GameError('This asset cannot be traded.');const limit=Number((R.orderSlots||{free:3,plus:4,gold:6,platinum:8})[c.entitlement]||3);
  if(game.world.orders.filter(o=>o.corporationId===c.id&&o.status==='open').length>=limit)throw new GameError(`Your ${limit} order slots are occupied.`);
  if(a.side==='buy')spend(c,bounded(q*price));else consume(h,asset.id,q);
  const o:Order={id:randomUUID(),corporationId:c.id,corporationName:c.name,regionId:rid,side:a.side,assetId:asset.id,quantity:q,remaining:q,price,createdAt:now,status:'open'};
  game.world.orders.push(o);matchOrder(game,o,now);note(c,`Placed ${a.side} order for ${q} ${asset.name}.`,now,'trade');break;}
 case 'order.cancel':{const o=game.world.orders.find(o=>o.id===a.id&&o.corporationId===c.id);if(!o)throw new GameError('Order not found.',404);cancelOrder(game,o);break;}
 case 'export.dispatch':{const dest=getHolding(c,a.toRegionId,game.world);if(a.toRegionId===rid)throw new GameError('Choose a different destination region.');const destRegion=game.world.regions.find(x=>x.id===a.toRegionId)!;if(!r.policies.includes('public_logistics_access'))requireFacility(h,['logistics_center'],'Build a logistics center at the origin.');if(!destRegion.policies.includes('public_logistics_access'))requireFacility(dest,['logistics_center'],'Build a logistics center at the destination.');
  const asset=getAsset(a.assetId),q=integer(a.quantity),truck=typeof a.truckId==='string'?a.truckId:'truck';if(!['truck','truck_plus'].includes(truck))throw new GameError('Choose a truck quality.');
  const slots=rules.export.maxDispatches;
  if(c.shipments.filter(s=>s.fromRegionId===rid&&s.status!=='claimed').length>=slots)throw new GameError('All dispatch slots are occupied until shipments are claimed.');
  consume(h,truck,1);consume(h,asset.id,q);const fuelId=truck==='truck_plus'?'gasoline_plus':'gasoline',fuel=exportFuel(assetPrice(asset.id),q,assetPrice(fuelId));consume(h,fuelId,fuel);
  const duration=Math.round((truck==='truck_plus'?rules.export.plusSeconds:rules.export.normalSeconds)*1000*(1-projectBonus(r,'exportSpeed',now)));c.shipments.push({id:randomUUID(),fromRegionId:rid,toRegionId:a.toRegionId,assetId:asset.id,quantity:q,truckId:truck,fuelId,fuel,dispatchedAt:now,arrivesAt:now+duration,status:'traveling'});c.stats.exports++;xp(c,20);break;}
 case 'export.claim':{const s=c.shipments.find(s=>s.id===a.id);if(!s)throw new GameError('Shipment not found.',404);if(s.status!=='arrived')throw new GameError(s.status==='claimed'?'Shipment already claimed.':'Shipment has not arrived yet.');stock(c.holdings[s.toRegionId]!,s.assetId,s.quantity);stock(c.holdings[s.fromRegionId]!,s.truckId,1);s.status='claimed';s.claimedAt=now;note(c,`Claimed shipment of ${s.quantity} ${s.assetId}.`,now);break;}
 case 'gift':{if(c.entitlement==='free')throw new GameError('Gifting requires a Plus, Gold or Platinum entitlement. A server administrator can grant tiers without payment.');const recipient=game.corps.find(x=>x.id===a.toCorporationId);if(!recipient||recipient.id===c.id)throw new GameError('Choose another corporation.');const q=integer(a.quantity);requireFacility(h,['logistics_center'],'Build a logistics center before gifting.');requireFacility(recipient.holdings[rid]!,['logistics_center'],'The recipient needs a logistics center in this region.');if(a.assetId==='cash'){spend(c,q);add(recipient,'cash',q);}else{getAsset(a.assetId);consume(h,a.assetId,q);recipient.inbox||=[];recipient.inbox.push({id:randomUUID(),regionId:rid,assetId:a.assetId,quantity:q,from:c.name,status:'pending',createdAt:now});}note(c,`Gifted ${q} ${a.assetId} to ${recipient.name}.`,now,'trade');note(recipient,`${c.name} sent ${q} ${a.assetId}.`,now,'trade');break;}
 case 'logistics.claim':{const selected=(c.inbox||[]).filter(i=>i.status==='pending'&&(a.all===true||i.id===a.id));claimExpansionInbox(c,selected,now);break;}
 case 'research.start':{const centers=h.facilities.filter(f=>f.type==='research_facility').length;if(!centers)throw new GameError('Build a research facility first.');if(h.research.some(p=>p.status!=='claimed'))throw new GameError('Claim the current regional research project before starting another.');const count=Math.min(rules.research.maxFacilities,centers);spend(c,Math.round(R.researchCost*(c.season.claimed.includes(7)?0.8:1)));consume(h,'energy',Math.round(R.researchEnergy*(c.season.claimed.includes(7)?0.8:1)));if(count>rules.research.extraAfter)consume(h,'energy_plus',Math.round((count-rules.research.extraAfter)*rules.research.extraPlusEnergy*(c.season.claimed.includes(7)?0.8:1)));
  const seconds=rules.research.minimumSeconds+roll(c)*(rules.research.maximumSeconds-rules.research.minimumSeconds)+(serviceActive(r,'university')?-600:0)+regionalEffect(r,'researchSeconds')-(c.space.vault.relic_of_haste||0)*R.researchHasteSecondsPerRelic-(c.season.claimed.includes(2)?1800:0);
  const duration=Math.max(1,Math.floor(seconds*1000));h.research.push({id:randomUUID(),tier:1,facilities:count,startedAt:now,readyAt:now+duration,status:'working',outcome:researchOutcome(c,count)});break;}
 case 'research.finish':{const p=h.research.find(p=>p.id===a.id&&p.status==='working');if(!p)throw new GameError('No working research project found.');add(c,'gratitude',-4);p.readyAt=now;p.status='ready';break;}
 case 'research.claim':{const p=h.research.find(p=>p.id===a.id);if(!p)throw new GameError('Project not found.',404);if(p.status!=='ready')throw new GameError(p.status==='claimed'?'Research already claimed.':'Research is still working.');for(const reward of p.outcome){if(reward.technologyId)stock(h,'blueprint_'+reward.technologyId,reward.quantity);else stock(h,reward.assetId,reward.quantity);}p.status='claimed';p.rewards=p.outcome;c.stats.researched+=p.facilities;xp(c,100*p.facilities);note(c,`Research completed: ${p.outcome.map((x:Dict)=>techMap.get(x.technologyId)?.name||assetMap.get(x.assetId)?.name).join(', ')}.`,now);break;}
 case 'technology.develop':{const t=techMap.get(a.technologyId);if(!t)throw new GameError('Unknown technology.');if((h.blueprints![t.id]||0)<1)throw new GameError('A matching blueprint is required.');spend(c,Number(t.cost||0));economics(c,h,t.materials||{});consume(h,'blueprint_'+t.id,1);stock(h,t.id,1);if(!c.technologies.includes(t.id))c.technologies.push(t.id);xp(c,50);break;}
 case 'technology.upgrade':{const asset=getAsset(a.technologyId);if(!asset.technologyId)throw new GameError('Choose a technology asset.');const t=techMap.get(asset.technologyId)!;if(asset.tier>=t.maxTier)throw new GameError('This technology is already at maximum tier.');const next=Array.from(assetMap.values()).find(x=>x.technologyId===t.id&&x.tier===asset.tier+1);if(!next)throw new GameError('No further upgrade is documented.');consume(h,asset.id,t.upgradeCount);stock(h,next.id,1);if(!c.technologies.includes(next.id))c.technologies.push(next.id);break;}
 case 'technology.install':case 'technology.uninstall':{const f=facility(h,a.id),{t}=installedTech(a.technologyId);if(!t)throw new GameError('Unknown technology.');if(type.endsWith('uninstall')){const index=f.installed.indexOf(a.technologyId);if(index<0)throw new GameError('Technology is not installed.');f.installed.splice(index,1);stock(h,a.technologyId,1);}else{if(!t.stackable&&h.facilities.some(x=>x.installed.some(id=>installedTech(id).t?.id===t.id)))throw new GameError('This technology cannot be stacked in one region.');const required=t.effect?.facility;if(required&&!['all','global'].includes(required)&&!f.type.includes(required))throw new GameError(`This technology requires a ${required.replaceAll('_',' ')} facility.`);if(h.facilities.reduce((n,x)=>n+x.installed.length,0)>=rules.baseTechnologySlots+Math.min(rules.maxBonusTechnologySlots,c.upgrades.tech_slots||0))throw new GameError('No free regional technology slots.');consume(h,a.technologyId,1);spend(c,t.installCost);f.installed.push(a.technologyId);}f.nextCycle=now+cycleMs(f,c,r);break;}
 case 'retail.configure':{if(!globalHas(c,'hq','headquarters'))throw new GameError('Build a headquarters first.');requireFacility(h,['retail_store'],'Build a retail store in this region.');const asset=getAsset(a.assetId);if(!asset.retail)throw new GameError('This asset cannot be sold at retail.');const price=integer(a.price,'Retail price');const existing=h.retail.find(row=>row.assetId===asset.id);if(existing)existing.price=price;else{if(h.retail.length>=rules.retail.slots)throw new GameError('Regional retail supports up to three products.');h.retail.push({assetId:asset.id,name:asset.name,price,nextSale:now+rules.retail.cycleSeconds*1000,sold:0,revenue:0});}break;}
 case 'retail.name':{if(c.entitlement==='free')throw new GameError('Custom retail names require a Plus or higher entitlement.');if(a.assetId){const row=h.retail.find(row=>row.assetId===a.assetId);if(!row)throw new GameError('Configure this product first.');row.name=text(a.name,'Product name',48);}else(h as any).retailName=text(a.name,'Retail name',48);break;}
 case 'retail.remove':{h.retail=h.retail.filter(row=>row.assetId!==a.assetId);break;}
 case 'service.fund':{const service=(services as unknown as Dict[]).find(s=>s.id===a.serviceId);if(!service)throw new GameError('Unknown regional service.');if(serviceActive(r,service.id))throw new GameError('This regional service is already fully funded.');const amount=Math.min(integer(a.amount,'Funding amount'),service.cost-(r.services[service.id]||0));spend(c,amount);r.services[service.id]=bounded((r.services[service.id]||0)+amount);xp(c,Math.min(100,Math.floor(amount/10000)));note(c,`Contributed to ${service.name} in ${r.name}.`,now);break;}
 case 'policy.vote':case 'policy.toggle':{const policy=(policies as unknown as Dict[]).find(p=>p.id===a.policyId);if(!policy)throw new GameError('Unknown policy.');if(!serviceActive(r,'region_office'))throw new GameError('Fully fund a region office first.');if(r.legislator!==c.id)throw new GameError('Only the elected regional legislator can change policies.');r.policyChangedAt||={};if((r.policyChangedAt[policy.id]||0)+policy.cooldownSeconds*1000>now)throw new GameError('This policy is on its 24-hour change cooldown.');const enabled=r.policies.includes(policy.id),next=enabled?r.policies.filter(id=>id!==policy.id):[...r.policies,policy.id];const list=(policies as unknown as Dict[]).filter(p=>next.includes(p.id));const budget=rules.governance.baseFundingPoints+list.reduce((n,p)=>n+Number(p.effect?.fundingPoints||0),0),used=list.reduce((n,p)=>n+p.fundingCost,0);if(used>budget)throw new GameError(`These policies require ${used} funding points, but the budget is ${budget}.`);r.policies=next;r.fundingPoints=budget-used;r.policyChangedAt[policy.id]=now;break;}
 case 'election.run':{if(!serviceActive(r,'region_office'))throw new GameError('Fully fund a region office before holding elections.');if(c.entitlement==='free'&&(c.rewards.vote||0)+rules.vote.boonSeconds*1000<=now)throw new GameError('Activate the voter boon before joining the ballot.');if(r.candidates.some(x=>x.corporationId===c.id))throw new GameError('You are already a candidate.');spend(c,rules.governance.candidateCost);r.candidates.push({corporationId:c.id,name:c.name,at:now});break;}
 case 'election.vote':{if(c.entitlement==='free'&&(c.rewards.vote||0)+rules.vote.boonSeconds*1000<=now)throw new GameError('Claim the supporter reward to activate the voter boon first.');if(!r.candidates.some(x=>x.corporationId===a.candidateId))throw new GameError('Candidate not found.');if(r.votes[c.id])throw new GameError('You have already voted in this election.');r.votes[c.id]=a.candidateId;break;}
 case 'prestige.preview':case 'liquidation.preview':{result.preview=preview(c,game.world,rid,type.startsWith('prestige')?'prestige':'liquidation',now);break;}
 case 'prestige.reset':case 'liquidation.reset':{const kind=type.startsWith('prestige')?'prestige':'liquidation';const p=preview(c,game.world,rid,kind,now);if(!p.eligible)throw new GameError('This reset is not yet eligible. Check the preview for requirements and cooldown.');
  resetExpansion(game,c,rid,kind,now);c.insights!.forceSample=true;
  for(const order of game.world.orders.filter(o=>o.corporationId===c.id&&o.status==='open'&&(kind==='prestige'||o.regionId===rid))){if(kind==='prestige'){order.status='cancelled';order.closedReason='prestige';}else cancelOrder(game,order);}
  if(kind==='prestige'){const stabilized=h.facilities.some(f=>f.installed.includes('quantum_stabilization'));const chance=stabilized?rules.space.stabilizedVaultRetention:rules.space.vaultRetention;const vault:Dict={};for(const[id,q]of Object.entries(c.space.vault)){let kept=0;for(let i=0;i<Number(q);i++)if(roll(c)<chance)kept++;vault[id]=kept;}
   add(c,'tokens',p.tokens);add(c,'score',p.score);xp(c,p.tokens*rules.prestige.xpPerToken);for(const id of Object.keys(c.holdings))c.holdings[id]=emptyHolding();const destination=c.holdings[rid]!;destination.land=R.initialLand+(c.season.claimed.includes(6)?20:0)+(c.season.claimed.includes(4)?5:0);c.cash=R.initialCash+(c.season.claimed.includes(5)?5000000:0)+(c.season.claimed.includes(3)?1000000:0);c.shipments=[];c.inbox=[];c.technologies=[];c.blueprints={};delete c.upgrades.land;c.lastPrestige=now;c.space={...c.space,orbital:false,station:{level:0,hull:0,xp:0},expedition:null,vault};
   if(p.netWorth>=rules.prestige.scoreDivisor)for(const [level,id]of [[8,'logistics_center'],[9,'air_traffic_control'],[10,'hq']] as const){if(c.season.claimed.includes(level)){destination.facilities.push({id:randomUUID(),type:id,level:0,xp:0,nextCycle:now+60000,enabled:true,plus:true,allowPlus:false,installed:[],costPaid:0,materialsPaid:{},builtAt:now});}}
  }
  else{const settled=preview(c,game.world,rid,'liquidation',now);add(c,'cash',settled.refund);c.holdings[rid]=emptyHolding();for(const s of c.shipments.filter(s=>s.status!=='claimed'&&(s.fromRegionId===rid||s.toRegionId===rid))){if(s.fromRegionId!==rid){stock(c.holdings[s.fromRegionId]!,s.assetId,s.quantity);stock(c.holdings[s.fromRegionId]!,s.truckId,1);}}c.shipments=c.shipments.filter(s=>s.fromRegionId!==rid&&s.toRegionId!==rid);c.lastLiquidation[rid]=now;for(const item of c.inbox||[])if(item.regionId===rid&&item.assetId!=='cash'&&item.status==='pending')item.status='liquidated';}
  note(c,`${kind==='prestige'?'Reincorporated':`Liquidated ${r.name}`}.`,now,'progression');result.preview=p;break;}
 case 'upgrade.buy':{const id=text(a.upgradeId,'Upgrade',30),costs:Dict={land:1,land_discount:1,tech_slots:rules.prestige.techSlotTokens,blueprint:rules.prestige.blueprintTokens};if(!costs[id])throw new GameError('Unknown token upgrade.');if(id==='land_discount'&&(c.upgrades[id]||0)>=rules.prestige.maxLandDiscountTokens)throw new GameError('Land discount is fully upgraded.');if(id==='tech_slots'&&(c.upgrades[id]||0)>=rules.maxBonusTechnologySlots)throw new GameError('All six technology slots are unlocked.');add(c,'tokens',-costs[id]);if(id==='blueprint'){const tech=text(a.technologyId,'Technology');if(!techMap.has(tech))throw new GameError('Choose a technology for the wildcard blueprint.');stock(h,'blueprint_'+tech,1);}else c.upgrades[id]=(c.upgrades[id]||0)+1;if(id==='land')h.land+=rules.prestige.landPerToken;break;}
 case 'reward.daily':case 'reward.weekly':case 'reward.vote':{const key=type.split('.')[1]!,duration=key==='weekly'?604800000:key==='vote'?rules.vote.cooldownSeconds*1000:86400000;if((c.rewards[key]||0)+duration>now)throw new GameError('This reward is still on cooldown.');if(now-c.createdAt<R.rewardEligibilitySeconds*1000)throw new GameError('Rewards unlock after your corporation is one minute old.');if(key==='weekly'&&!c.season.claimed.includes(1))throw new GameError('Claim season level one to unlock weekly rewards.');c.rewards[key]=now;const tier=(rules.entitlements as Dict)[c.entitlement],multiplier=key==='vote'?tier.voteMultiplier:1;const cash=(key==='weekly'?R.weeklyRewardCash:key==='vote'?rules.vote.cash:R.dailyRewardCash)*multiplier;add(c,'cash',cash);add(c,'gratitude',(key==='vote'?rules.vote.gratitude:1)*multiplier);if(key==='weekly')add(c,'tokens',tier.weeklyTokens);xp(c,key==='weekly'?200:key==='vote'?rules.vote.seasonXp*multiplier:50);note(c,`Claimed ${key==='vote'?'standalone supporter':key} reward.`,now,'reward');break;}
 case 'challenge.claim':{const id=a.challengeId||'production',challenge=rules.season.challenges.find(x=>x.id===id);if(!challenge)throw new GameError('Unknown daily challenge.');const unlocked=rules.season.challenges.slice(0,(rules.entitlements as Dict)[c.entitlement].dailyChallenges);if(!unlocked.some(x=>x.id===id))throw new GameError('This challenge requires a higher entitlement tier.');const day=Math.floor(now/86400000),key=`${day}:${challenge.metric==='cycles'?'produce':challenge.metric}`,claimed=`${day}:claimed:${id}`;if((c.season.challenges[key]||0)<challenge.target)throw new GameError(`Complete the daily target of ${challenge.target} ${challenge.metric} first.`);if(c.season.challenges[claimed])throw new GameError('Daily challenge already claimed.');c.season.challenges[claimed]=1;if(id==='production')c.season.challenges[`${day}:produce:claimed`]=1;xp(c,challenge.xp);add(c,'cash',R.dailyChallengeCash);break;}
 case 'season.claim':{const level=integer(a.level,'Season level',1,rules.season.xpThresholds.length);if(now<game.world.season.startsAt||now>=game.world.season.endsAt)throw new GameError('This season is not active.');if(c.season.xp<rules.season.xpThresholds[level-1]!)throw new GameError('Earn more season XP first.');if(c.season.claimed.includes(level))throw new GameError('Season reward already claimed.');c.season.claimed.push(level);add(c,'cash',level*R.seasonRewardCashPerLevel);break;}
 case 'space.launch':{requireFacility(h,['rocket_launch_pad'],'Build a rocket launch pad first.');if(c.space.orbital)throw new GameError('Your corporation already has orbital presence.');consume(h,'rocket',1);consume(h,'rocket_fuel',rules.space.launchFuel);c.space.orbital=true;xp(c,200);note(c,'Established orbital presence.',now,'space');break;}
 case 'space.station.build':{requireFacility(h,['rocket_launch_pad'],'Build a rocket launch pad first.');if(!c.space.orbital)throw new GameError('Launch a rocket to establish orbital presence first.');if(c.space.station.level)throw new GameError('Station already built.');economics(c,h,rules.space.station.materials);c.space.station={level:1,hull:R.initialStationHull,xp:0};break;}
 case 'space.station.upgrade':{const station=c.space.station;if(!station.level)throw new GameError('Build a space station first.');if(station.level>=rules.space.maxStationLevel)throw new GameError('Station is at maximum level.');const required=station.level*R.stationUpgradeXpPerLevel;if((station.xp||0)<required)throw new GameError(`Earn ${required} expedition points before upgrading.`);station.xp-=required;station.level++;break;}
 case 'space.station.repair':{const station=c.space.station;if(!station.level)throw new GameError('Build a space station first.');if(station.hull>=R.initialStationHull)throw new GameError('Station hull is already fully repaired.');consume(h,'space_station_parts',Math.ceil((R.initialStationHull-station.hull)*R.repairPartsPerHull));station.hull=R.initialStationHull;break;}
 case 'space.expedition':{if(!c.space.orbital||!c.space.station.level)throw new GameError('Establish orbital presence and build a station first.');if(c.space.expedition&&c.space.expedition.status!=='claimed')throw new GameError('Claim your previous expedition first.');if(c.space.station.hull<=0)throw new GameError('Repair your station before another expedition.');const difficulty=integer(a.difficulty??1,'Expedition difficulty',1,5),spec=rules.space.expeditions[difficulty-1]!;consume(h,spec.coordinateId,1);consume(h,'rocket',spec.rocket);consume(h,'rocket_fuel',spec.fuel);const chance=Math.min(1,spec.baseSuccess+c.space.station.level*rules.space.levelSuccessBonus),success=roll(c)<chance;
  const relics=['relic_of_haste','relic_of_prestige','relic_of_efficiency','relic_of_knowledge'];const relicId=relics[Math.floor(roll(c)*relics.length)]!,reward=success?difficulty:0,rocketReturned=!success&&roll(c)<0.5;
  c.space.expedition={id:randomUUID(),difficulty,regionId:rid,successChance:chance,startedAt:now,readyAt:now+spec.durationSeconds*1000,status:'traveling',outcome:{success,relicId,relics:reward,damage:success?0:spec.failureDamage,rocketReturned,xp:spec.xp}};break;}
 case 'space.claim':{const e=c.space.expedition;if(!e||e.status!=='ready')throw new GameError('No expedition reward is ready.');const dest=c.holdings[e.regionId]||h;if(e.outcome.relics)stock(dest,e.outcome.relicId,e.outcome.relics);if(e.outcome.rocketReturned)stock(dest,'rocket',1);c.space.relics+=e.outcome.relics;c.space.station.hull=Math.max(0,c.space.station.hull-e.outcome.damage);c.space.station.xp=(c.space.station.xp||0)+e.outcome.xp;e.status='claimed';e.result=e.outcome;xp(c,e.outcome.success?200:25);note(c,`Expedition ${e.outcome.success?'succeeded':'failed'}; recovered ${e.outcome.relics} relics.`,now,'space');break;}
 case 'space.relic':{const id=text(a.assetId,'Relic');if(id!=='relic_of_knowledge')throw new GameError('Haste, prestige and efficiency relics activate while stored in the quantum vault. Knowledge relics are consumed to finish research.');const projects=Object.values(c.holdings).flatMap(h=>h.research).filter(p=>p.status==='working');if(!projects.length)throw new GameError('Start research before using a knowledge relic.');consume(h,id,1);for(const p of projects){p.readyAt=now;p.status='ready';}break;}
 case 'space.vault':{if(!c.space.station.level)throw new GameError('Build a space station to access the quantum vault.');const asset=getAsset(a.assetId),q=integer(a.quantity);if(a.withdraw===true){if((c.space.vault[asset.id]||0)<q)throw new GameError('Not enough assets in the vault.');c.space.vault[asset.id]-=q;stock(h,asset.id,q);}else{const capacity=c.space.station.level*R.vaultBaseCapacity+c.space.relics*R.vaultCapacityPerRelic,used=Object.values(c.space.vault).reduce((n:any,v:any)=>n+v,0) as number;if(used+q>capacity)throw new GameError(`Quantum vault capacity is ${capacity} units.`);consume(h,asset.id,q);c.space.vault[asset.id]=(c.space.vault[asset.id]||0)+q;}break;}
 case 'settings.update':{if(a.name!==undefined){const name=text(a.name,'Corporation name',48);if(name!==c.name){add(c,'gratitude',-2);c.name=name;}}if(a.motto!==undefined){if(typeof a.motto!=='string'||a.motto.length>160)throw new GameError('Motto must be at most 160 characters.');if(c.motto!==a.motto){add(c,'gratitude',-1);c.motto=a.motto;}}if(a.privacy!==undefined){if(typeof a.privacy!=='boolean')throw new GameError('Privacy must be a boolean.');c.privacy=a.privacy;}if(a.notifications!==undefined){if(typeof a.notifications!=='boolean')throw new GameError('Notifications must be a boolean.');(c as any).notifications=a.notifications;}break;}
 default:throw new GameError('Unknown action.',404);
 }
 return result;
}
