import pg from 'pg';
import { readFile, readdir } from 'node:fs/promises';
import { fileURLToPath } from 'node:url';
import { createHash } from 'node:crypto';
import { advance, createWorld, snapshot } from './engine.js';
import { executeAction } from './actions.js';
import { Corp, Dict, Game, GameError } from './types.js';
import { recordInsights, makeReturnSummary, captureReturnBaseline } from './insights.js';
import { onboardingProgress, planProduction } from './planning.js';
import { productionTarget } from './production-targets.js';

export const pool=new pg.Pool({connectionString:process.env.DATABASE_URL||(process.env.PGHOST?undefined:'postgres://idlecorp:idlecorp@localhost:5432/idlecorp'),max:10});
export const WORLD_LOCK=19014349;
export async function migrate(){const directory=new URL('../migrations/',import.meta.url);const names=(await readdir(directory)).filter(name=>/^\d+_.*\.sql$/.test(name)).sort();await transaction(async db=>{for(const name of names)await db.query(await readFile(fileURLToPath(new URL(name,directory)),'utf8'));await db.query('INSERT INTO world(id,state) VALUES(1,$1) ON CONFLICT DO NOTHING',[JSON.stringify(createWorld(Date.now()))]);});}
export async function transaction<T>(fn:(db:pg.PoolClient)=>Promise<T>):Promise<T>{const db=await pool.connect();try{await db.query('BEGIN');await db.query('SELECT pg_advisory_xact_lock($1)',[WORLD_LOCK]);const result=await fn(db);await db.query('COMMIT');return result;}catch(error){await db.query('ROLLBACK');throw error;}finally{db.release();}}
export async function loadGame(db:pg.PoolClient):Promise<Game>{const w=await db.query('SELECT state FROM world WHERE id=1 FOR UPDATE');const cs=await db.query('SELECT state FROM corporations ORDER BY id FOR UPDATE');return {world:w.rows[0].state,corps:cs.rows.map(row=>row.state)};}
export async function saveGame(db:pg.PoolClient,game:Game){recordInsights(game,Date.now());await db.query('UPDATE world SET state=$1 WHERE id=1',[JSON.stringify(game.world)]);for(const c of game.corps)await db.query('UPDATE corporations SET state=$1,revision=$2 WHERE id=$3',[JSON.stringify(c),game.world.revision,c.id]);}
function summary(c:Corp){return {cash:c.cash,tokens:c.tokens,score:c.score,gratitude:c.gratitude,inventory:Object.fromEntries(Object.entries(c.holdings).map(([id,h])=>[id,h.inventory])),facilities:Object.values(c.holdings).reduce((n,h)=>n+h.facilities.length,0),inbox:c.inbox||[],shipments:c.shipments,commitments:c.commitments||{cash:0,assets:{}}};}
export async function getSnapshot(accountId:string){return transaction(async db=>{const game=await loadGame(db),c=game.corps.find(x=>x.id===accountId);if(!c)throw new GameError('Corporation not found.',404);const now=Date.now();const catchup=advance(game,now);if(catchup.events)game.world.revision++;const summary=makeReturnSummary(game,c,now);captureReturnBaseline(c,now);c.lastSeenAt=now;c.lastSeenProduced=c.stats.produced;await saveGame(db,game);return snapshot(game,c,now,{returnSummary:{...summary,processedEvents:catchup.events},onboarding:onboardingProgress(game,c,now)});});}
export async function getPlan(accountId:string,options:{regionId?:string;facilityId?:string;quantity?:number}){return transaction(async db=>{const game=await loadGame(db),c=game.corps.find(x=>x.id===accountId);if(!c)throw new GameError('Corporation not found.',404);const now=Date.now(),result=advance(game,now);if(result.events)game.world.revision++;const plan=planProduction(game,c,{...options,regionId:options.regionId||game.world.regions[0]!.id,now});await saveGame(db,game);return plan;});}
export async function getProductionTarget(accountId:string,options:Dict){return transaction(async db=>{const game=await loadGame(db),c=game.corps.find(x=>x.id===accountId);if(!c)throw new GameError('Corporation not found.',404);const now=Date.now(),result=advance(game,now);if(result.events)game.world.revision++;const plan=productionTarget(game,c,options,now);await saveGame(db,game);return plan;});}
function canonicalize(value:any):any{if(Array.isArray(value))return value.map(canonicalize);if(value&&typeof value==='object')return Object.fromEntries(Object.keys(value).sort().map(key=>[key,canonicalize(value[key])]));return value;}
export async function performAction(accountId:string,key:string,payload:Dict){return transaction(async db=>{
 const canonical=JSON.stringify(canonicalize(payload));const hash=createHash('sha256').update(canonical).digest('hex');
 const prior=await db.query('SELECT payload_hash,response FROM idempotency WHERE account_id=$1 AND key=$2',[accountId,key]);if(prior.rowCount){if(prior.rows[0].payload_hash!==hash)throw new GameError('Idempotency key was already used for a different request.',409);return prior.rows[0].response;}
 const game=await loadGame(db),c=game.corps.find(x=>x.id===accountId);if(!c)throw new GameError('Corporation not found.',404);const now=Date.now();advance(game,now);const beforeAll=new Map(game.corps.map(x=>[x.id,structuredClone(summary(x))]));const before=beforeAll.get(c.id)!;const extra=executeAction(game,c,payload,now);game.world.revision++;
 await saveGame(db,game);const response=snapshot(game,c,now,{...extra,onboarding:onboardingProgress(game,c,now)});await db.query('INSERT INTO idempotency(account_id,key,payload_hash,response) VALUES($1,$2,$3,$4)',[accountId,key,hash,JSON.stringify(response)]);
 const counterparties=game.corps.filter(x=>x.id!==c.id&&JSON.stringify(beforeAll.get(x.id))!==JSON.stringify(summary(x))).map(x=>({id:x.id,before:beforeAll.get(x.id),after:summary(x)}));
 await db.query('INSERT INTO economic_audit(account_id,action,region_id,payload,changes,revision) VALUES($1,$2,$3,$4,$5,$6)',[accountId,payload.type,payload.regionId||null,JSON.stringify(payload),JSON.stringify({before,after:summary(c),counterparties}),game.world.revision]);return response;
 });}
export async function tick(){return transaction(async db=>{const game=await loadGame(db),now=Date.now();const result=advance(game,now);if(result.events){game.world.revision++;if(now-(game.world.lastAuditAt||0)>=60000){const totals=game.corps.reduce((n,c)=>({produced:n.produced+c.stats.produced,earned:n.earned+c.stats.earned}),{produced:0,earned:0}),previous=game.world.auditTotals||{produced:0,earned:0};await db.query('INSERT INTO economic_audit(action,payload,changes,revision) VALUES($1,$2,$3,$4)',['simulation.advance',JSON.stringify({from:game.world.lastAuditAt||now,to:now,corporations:game.corps.length}),JSON.stringify({produced:totals.produced-previous.produced,earned:totals.earned-previous.earned}),game.world.revision]);game.world.auditTotals=totals;game.world.lastAuditAt=now;}await saveGame(db,game);}return {revision:game.world.revision,events:result.events};});}
