import { randomUUID } from 'node:crypto';
import { expansionRules } from '../../../packages/rules/src/expansion.js';
import { add, assetPrice, bounded, consume, getAsset, getHolding, integer, marketPrice, note, requireFacility, spend, stock } from './engine.js';
import { normalizeEnhancements, notifyCorporation } from './insights.js';
import { Corp, Dict, Game, GameError, Region } from './types.js';

function activeContract(x:Dict){return x.status==='open'||x.status==='accepted';}
function corporation(game:Game,id:string){const c=game.corps.find(c=>c.id===id);if(!c)throw new GameError('Corporation no longer exists.',404);return c;}
function enabled(game:Game){if(!game.world.expansionEnabled)throw new GameError('The optional expansion is disabled. Existing commitments may still be settled, cancelled, or claimed.');}
function commitment(c:Corp,cash:number,materials:Record<string,number>,direction:1|-1){c.commitments??={cash:0,assets:{}};c.commitments.cash=bounded(c.commitments.cash+cash*direction);if(c.commitments.cash<0)throw new GameError('Escrow accounting mismatch.');for(const[id,q]of Object.entries(materials)){c.commitments.assets[id]=bounded((c.commitments.assets[id]||0)+q*direction);if(c.commitments.assets[id]<0)throw new GameError('Material escrow accounting mismatch.');}}
function inbox(c:Corp,regionId:string,assetId:string,quantity:number,source:string,relatedId:string,now:number,message:string){if(!quantity)return;c.inbox??=[];c.inbox.push({id:randomUUID(),regionId,assetId,quantity,source,relatedId,from:message,status:'pending',createdAt:now});}
function closeContract(game:Game,contract:Dict,status:string,reason:string,now:number){if(!activeContract(contract))return;const buyer=corporation(game,contract.buyerId),refund=contract.escrowCash;commitment(buyer,refund,{},-1);inbox(buyer,contract.buyerRegionId,'cash',refund,'contract',contract.id,now,'Unspent contract escrow');contract.escrowCash=0;contract.status=status;contract.closedAt=now;contract.closedReason=reason;contract.refundedCash=(contract.refundedCash||0)+refund;
  notifyCorporation(buyer,'contract',`Supply contract ${status}`,`${reason} ${refund} cents of unspent escrow are available in your inbox.`,now,contract.id);
  if(contract.sellerId)notifyCorporation(corporation(game,contract.sellerId),'contract',`Supply contract ${status}`,reason,now,contract.id);
}
function removeContribution(game:Game,project:Dict,contribution:Dict,now:number){const c=corporation(game,contribution.corporationId);commitment(c,contribution.cash,contribution.materials,-1);inbox(c,project.regionId,'cash',contribution.cash,'project_refund',project.id,now,`${project.name} contribution refund`);for(const[id,q]of Object.entries(contribution.materials))inbox(c,project.regionId,id,Number(q),'project_refund',project.id,now,`${project.name} material refund`);project.contributed.cash-=contribution.cash;for(const[id,q]of Object.entries(contribution.materials))project.contributed.materials[id]-=Number(q);project.contributors=project.contributors.filter((x:Dict)=>x.corporationId!==c.id);notifyCorporation(c,'project','Contribution returned',`${project.name}: your pooled contribution is ready to reclaim.`,now,project.id);}
function closeProject(game:Game,project:Dict,status:string,now:number){for(const contribution of [...project.contributors])removeContribution(game,project,contribution,now);project.status=status;project.closedAt=now;}
export function projectBonus(r:Region,key:'productionSpeed'|'happiness'|'exportSpeed',now:number){const caps={productionSpeed:expansionRules.projects.maximumProductionBonus,happiness:expansionRules.projects.maximumHappinessBonus,exportSpeed:expansionRules.projects.maximumExportBonus};return Math.min(caps[key],(r.projectBenefits||[]).filter((x:Dict)=>x.expiresAt>now).reduce((n:number,x:Dict)=>n+Number(x.effect[key]||0),0));}
function updateProjectHappiness(r:Region,now:number){const next=projectBonus(r,'happiness',now),base=r.happiness-Number(r.projectHappiness||0);r.happiness=Math.max(10,Math.min(100,base+next));r.projectHappiness=r.happiness-base;}
function completeProject(game:Game,project:Dict,now:number){project.status='completed';project.completedAt=now;project.benefitExpiresAt=now+project.durationSeconds*1000;const r=game.world.regions.find(r=>r.id===project.regionId)!;r.projectBenefits??=[];r.projectBenefits.push({projectId:project.id,typeId:project.typeId,expiresAt:project.benefitExpiresAt,effect:project.effect});updateProjectHappiness(r,now);
  for(const contribution of project.contributors){const c=corporation(game,contribution.corporationId);commitment(c,contribution.cash,contribution.materials,-1);notifyCorporation(c,'project','Regional project completed',`${project.name} is complete. Its regional benefit is now active.`,now,project.id);}
}
export function nextExpansionEvent(game:Game){let at=Infinity;for(const x of game.world.contracts||[])if(activeContract(x))at=Math.min(at,x.deadline);for(const p of game.world.projects||[])if(p.status==='funding')at=Math.min(at,p.deadline);for(const r of game.world.regions)for(const b of r.projectBenefits||[])at=Math.min(at,b.expiresAt);return at;}
export function settleExpansion(game:Game,now:number){let events=0;for(const x of game.world.contracts||[])if(activeContract(x)&&x.deadline<=now){closeContract(game,x,'expired','Delivery deadline passed.',x.deadline);events++;}for(const p of game.world.projects||[])if(p.status==='funding'&&p.deadline<=now){closeProject(game,p,'expired',p.deadline);events++;}for(const r of game.world.regions){const before=(r.projectBenefits||[]).length;r.projectBenefits=(r.projectBenefits||[]).filter((b:Dict)=>b.expiresAt>now);if(before!==r.projectBenefits.length){updateProjectHappiness(r,now);events++;}}return events;}
export function resetExpansion(game:Game,c:Corp,regionId:string,kind:'prestige'|'liquidation',now:number){
  for(const x of game.world.contracts||[])if(activeContract(x)&&((x.buyerId===c.id&&(kind==='prestige'||x.buyerRegionId===regionId))||(x.sellerId===c.id&&(kind==='prestige'||x.sellerRegionId===regionId))))closeContract(game,x,'cancelled',`${c.name} ${kind==='prestige'?'reincorporated':'liquidated the associated region'}.`,now);
  for(const p of game.world.projects||[])if(p.status==='funding'&&(kind==='prestige'||p.regionId===regionId)){const contribution=p.contributors.find((x:Dict)=>x.corporationId===c.id);if(contribution)removeContribution(game,p,contribution,now);}
}
export function expansionResetPreview(game:Game,c:Corp,regionId:string,kind:'prestige'|'liquidation',now:number){const contracts=(game.world.contracts||[]).filter(x=>activeContract(x)&&((x.buyerId===c.id&&(kind==='prestige'||x.buyerRegionId===regionId))||(x.sellerId===c.id&&(kind==='prestige'||x.sellerRegionId===regionId))));const projects=(game.world.projects||[]).filter(p=>p.status==='funding'&&(kind==='prestige'||p.regionId===regionId)&&p.contributors.some((x:Dict)=>x.corporationId===c.id));let cash=contracts.filter(x=>x.buyerId===c.id).reduce((n,x)=>n+x.escrowCash,0),materialsValue=0;
 for(const p of projects){const contribution=p.contributors.find((x:Dict)=>x.corporationId===c.id),r=game.world.regions.find(r=>r.id===p.regionId)!;cash+=contribution.cash;for(const[id,q]of Object.entries(contribution.materials))materialsValue+=marketPrice(r,id,'sell',now)*Number(q);}
 return {cancelledContracts:contracts.length,withdrawnProjects:projects.length,refundableCash:cash,liquidatedMaterialsValue:kind==='liquidation'?materialsValue:0,note:kind==='prestige'?'Unspent escrow and pooled contributions return before ordinary balances are reset. Other corporations retain earned payouts and receive any refunds owed.':'Unspent cash returns to the global inbox; withdrawn local project materials are included in the liquidation value.'};
}
export function claimExpansionInbox(c:Corp,items:Dict[],now:number){if(!items.length)throw new GameError('No matching unclaimed deliveries or refunds found.');for(const item of items){const h=c.holdings[item.regionId];if(!h)throw new GameError('Delivery region is not available.');if(item.assetId==='cash')add(c,'cash',item.quantity);else{if(item.source!=='project_refund'&&(item.source!=='contract'||expansionRules.contracts.requiresLogistics))requireFacility(h,['logistics_center'],'Build a logistics center in the delivery region before claiming.');stock(h,item.assetId,item.quantity);}item.status='claimed';item.claimedAt=now;}}
export function expansionAction(game:Game,c:Corp,a:Dict,now:number):boolean {
 if(!a.type?.startsWith('contract.')&&!a.type?.startsWith('project.'))return false;normalizeEnhancements(game);const rid=typeof a.regionId==='string'?a.regionId:game.world.regions[0]!.id,h=getHolding(c,rid,game.world);
 switch(a.type){
  case 'contract.create':{enabled(game);if(expansionRules.contracts.requiresLogistics)requireFacility(h,['logistics_center'],'A logistics center is required in the delivery region.');const asset=getAsset(a.assetId);if(asset.tradeable===false)throw new GameError('This asset cannot be offered in supply contracts.');const quantity=integer(a.quantity),price=integer(a.price,'Unit price'),seconds=integer(a.deadlineSeconds??86400,'Delivery window',expansionRules.contracts.minimumSeconds,expansionRules.contracts.maximumSeconds);if(game.world.contracts!.filter(x=>activeContract(x)&&x.buyerId===c.id).length>=expansionRules.contracts.maximumActivePerCorporation)throw new GameError('You have reached the active supply-contract limit.');const value=bounded(quantity*price);spend(c,value);commitment(c,value,{},1);game.world.contracts!.push({id:randomUUID(),buyerId:c.id,buyerName:c.name,buyerRegionId:rid,assetId:asset.id,quantity,delivered:0,price,escrowCash:value,createdAt:now,deadline:now+seconds*1000,status:'open',deliveries:[]});note(c,`Posted a supply contract for ${quantity} ${asset.name}.`,now,'contract');break;}
  case 'contract.accept':{enabled(game);const x=game.world.contracts!.find(x=>x.id===a.id);if(!x)throw new GameError('Supply contract not found.',404);if(x.status!=='open'||x.deadline<=now)throw new GameError('This contract is no longer open.');if(x.buyerId===c.id)throw new GameError('Another corporation must supply your contract.');if(game.world.contracts!.filter(x=>x.status==='accepted'&&x.sellerId===c.id).length>=expansionRules.contracts.maximumActivePerCorporation)throw new GameError('You have reached the active supply-contract limit.');if(expansionRules.contracts.requiresLogistics)requireFacility(h,['logistics_center'],'A logistics center is required in the supply region.');x.sellerId=c.id;x.sellerName=c.name;x.sellerRegionId=rid;x.status='accepted';x.acceptedAt=now;notifyCorporation(corporation(game,x.buyerId),'contract','Supplier accepted',`${c.name} accepted your ${getAsset(x.assetId).name} supply contract.`,now,x.id);break;}
  case 'contract.deliver':{const x=game.world.contracts!.find(x=>x.id===a.id);if(!x||x.sellerId!==c.id)throw new GameError('Accepted supply contract not found.',404);if(x.status!=='accepted'||x.deadline<=now)throw new GameError('The contract is closed or its deadline has passed.');const quantity=integer(a.quantity,'Delivery quantity',1,x.quantity-x.delivered),value=bounded(quantity*x.price),fee=Math.floor(value*expansionRules.contracts.feeRate),buyer=corporation(game,x.buyerId);const origin=c.holdings[x.sellerRegionId]!;consume(origin,x.assetId,quantity);commitment(buyer,value,{},-1);inbox(buyer,x.buyerRegionId,x.assetId,quantity,'contract',x.id,now,`${c.name} contract delivery`);inbox(c,x.sellerRegionId,'cash',value-fee,'contract',x.id,now,'Supply contract payment');x.delivered+=quantity;x.escrowCash-=value;x.deliveries.push({id:randomUUID(),at:now,quantity,value,fee});if(x.delivered===x.quantity){x.status='completed';x.completedAt=now;}notifyCorporation(buyer,'contract','Supply delivery ready',`${quantity} ${getAsset(x.assetId).name} is ready to claim.`,now,x.id);notifyCorporation(c,'contract','Contract payment ready',`${value-fee} cents are ready to claim for your delivery.`,now,x.id);break;}
  case 'contract.cancel':{const x=game.world.contracts!.find(x=>x.id===a.id);if(!x||![x.buyerId,x.sellerId].includes(c.id))throw new GameError('Supply contract not found.',404);if(!activeContract(x))throw new GameError('This contract is already closed.');closeContract(game,x,'cancelled',`${c.name} cancelled the remaining undelivered commitment.`,now);break;}
  case 'contract.claim':{claimExpansionInbox(c,(c.inbox||[]).filter(i=>i.status==='pending'&&i.source==='contract'&&i.relatedId===a.id),now);break;}
  case 'project.create':{enabled(game);if(h.land<10)throw new GameError('Own at least ten land in the region before proposing a project.');const spec=expansionRules.projectTypes.find(x=>x.id===a.projectTypeId);if(!spec)throw new GameError('Unknown cooperative project type.');const active=game.world.projects!.filter(p=>p.status==='funding'&&p.regionId===rid);if(active.length>=expansionRules.projects.maximumActivePerRegion||active.some(p=>p.typeId===spec.id))throw new GameError('This region already has that project open or its project slots are full.');if((game.world.regions.find(r=>r.id===rid)!.projectBenefits||[]).some((b:Dict)=>b.typeId===spec.id&&b.expiresAt>now))throw new GameError('That project benefit is already active.');game.world.projects!.push({id:randomUUID(),typeId:spec.id,name:spec.name,regionId:rid,creatorId:c.id,createdAt:now,deadline:now+expansionRules.projects.deadlineSeconds*1000,status:'funding',requirements:structuredClone(spec.requirements),contributed:{cash:0,materials:{}},contributors:[],effect:structuredClone(spec.effect),durationSeconds:spec.durationSeconds});break;}
  case 'project.contribute':{enabled(game);const p=game.world.projects!.find(x=>x.id===a.id);if(!p)throw new GameError('Project not found.',404);if(p.status!=='funding'||p.deadline<=now)throw new GameError('This project is no longer accepting contributions.');if(rid!==p.regionId)throw new GameError('Select the project region to contribute.');const cash=integer(a.cash??0,'Cash contribution',0,p.requirements.cash-p.contributed.cash);if(a.materials!==undefined&&(!a.materials||typeof a.materials!=='object'||Array.isArray(a.materials)))throw new GameError('Materials must be an asset-to-quantity object.');const materials:Record<string,number>={};for(const[id,value]of Object.entries(a.materials||{})){if(!Object.hasOwn(p.requirements.materials,id))throw new GameError('This material is not required by the project.');const q=integer(value,`${id} contribution`,0,p.requirements.materials[id]-(p.contributed.materials[id]||0));if(q)materials[id]=q;}if(!cash&&!Object.keys(materials).length)throw new GameError('Choose a positive contribution.');spend(c,cash);for(const[id,q]of Object.entries(materials))consume(h,id,q);commitment(c,cash,materials,1);let own=p.contributors.find((x:Dict)=>x.corporationId===c.id);if(!own){own={corporationId:c.id,name:c.name,cash:0,materials:{}};p.contributors.push(own);}own.cash+=cash;p.contributed.cash+=cash;for(const[id,q]of Object.entries(materials)){own.materials[id]=(own.materials[id]||0)+q;p.contributed.materials[id]=(p.contributed.materials[id]||0)+q;}own.updatedAt=now;if(p.contributed.cash===p.requirements.cash&&Object.entries(p.requirements.materials).every(([id,q])=>(p.contributed.materials[id]||0)===q))completeProject(game,p,now);break;}
  case 'project.withdraw':{const p=game.world.projects!.find(x=>x.id===a.id);if(!p)throw new GameError('Project not found.',404);if(p.status!=='funding')throw new GameError('Completed or closed contributions cannot be withdrawn.');const own=p.contributors.find((x:Dict)=>x.corporationId===c.id);if(!own)throw new GameError('You have no pooled contribution to withdraw.');removeContribution(game,p,own,now);break;}
  case 'project.cancel':{const p=game.world.projects!.find(x=>x.id===a.id&&x.creatorId===c.id);if(!p)throw new GameError('Project not found or you are not its proposer.',404);if(p.status!=='funding')throw new GameError('This project is already closed.');closeProject(game,p,'cancelled',now);break;}
  case 'project.claim':{claimExpansionInbox(c,(c.inbox||[]).filter(i=>i.status==='pending'&&i.source==='project_refund'&&i.relatedId===a.id),now);break;}
  default:throw new GameError('Unknown expansion action.',404);
 }
 return true;
}
export function expansionSnapshot(game:Game,c:Corp){return {enabled:!!game.world.expansionEnabled,rules:expansionRules,contracts:(game.world.contracts||[]).filter(x=>activeContract(x)||x.buyerId===c.id||x.sellerId===c.id).slice(-150),projects:(game.world.projects||[]).slice(-100),commitments:c.commitments||{cash:0,assets:{}}};}
export function committedValue(c:Corp){return (c.commitments?.cash||0)+Object.entries(c.commitments?.assets||{}).reduce((n,[id,q])=>n+assetPrice(id)*q,0);}


