import { randomUUID } from 'node:crypto';
import { assetMap, buildCost, buyingLimit, facilityMap, getAsset, landCost, marketPrice, MAX, recipe } from './engine.js';
import { facilityFlow, flowTotals, regionalFlows, resourceBalances, type FacilityFlow } from './resource-balances.js';
import { GameError, type Corp, type Dict, type Facility, type Game } from './types.js';

export interface TargetOptions { regionId:string; assetId:string; mode:'rate'|'stock'; amount:number; source:'produce'|'buy'; horizonMinutes:number; choices:Record<string,'produce'|'buy'>; producerChoices:Record<string,string>; }
export const productionTargetLimits={minimumRate:0.000001,maximumRate:1000000,maximumStock:MAX,minimumHorizonMinutes:1,maximumHorizonMinutes:10080,maximumPlans:20,maximumNameLength:60,maximumChoices:50,maximumFacilities:2000};
const EPS=1e-8;
const add=(map:Record<string,number>,id:string,n:number)=>{map[id]=(map[id]||0)+n;};
const title=(id:string)=>assetMap.get(id)?.name||'Capital';
function record(value:unknown,label:string){if(value===undefined)return {};if(!value||typeof value!=='object'||Array.isArray(value)||Object.keys(value).length>productionTargetLimits.maximumChoices)throw new GameError(`${label} must be an object with at most 50 choices.`);return value as Dict;}
export function validateTarget(game:Game,c:Corp,a:Dict):TargetOptions {
 const regionId=a.regionId??game.world.regions[0]!.id;if(typeof regionId!=='string'||!game.world.regions.some(r=>r.id===regionId)||!c.holdings[regionId])throw new GameError('Choose a valid region.');
 getAsset(a.assetId);if(!['rate','stock'].includes(a.mode))throw new GameError('Target mode must be rate or stock.');if(!['produce','buy'].includes(a.source))throw new GameError('Target source must be produce or buy.');
 if(typeof a.amount!=='number'||!Number.isFinite(a.amount)||a.amount<=0||a.amount>(a.mode==='rate'?productionTargetLimits.maximumRate:MAX)||a.mode==='rate'&&a.amount<productionTargetLimits.minimumRate||a.mode==='stock'&&!Number.isSafeInteger(a.amount))throw new GameError('Enter a positive rate from 0.000001 to 1,000,000 per minute, or a whole stock target within the inventory limit.');
 const horizonMinutes=a.horizonMinutes??60;if(typeof horizonMinutes!=='number'||!Number.isFinite(horizonMinutes)||horizonMinutes<1||horizonMinutes>10080)throw new GameError('Planning horizon must be between 1 and 10,080 minutes.');
 const choices:TargetOptions['choices']={},producerChoices:Record<string,string>={};for(const[id,source]of Object.entries(record(a.choices,'Source choices'))){getAsset(id);if(!['produce','buy'].includes(source))throw new GameError('Each resource source must be produce or buy.');choices[id]=source;}
 for(const[id,type]of Object.entries(record(a.producerChoices,'Producer choices'))){const asset=getAsset(id),d=facilityMap.get(type),outputs=d?recipe(exemplar(d.id,c.lastProcessed),c,game.world.regions.find(r=>r.id===regionId)!).outputs:{};if(!d||!Number(outputs[id]||outputs[asset.baseAsset||id]))throw new GameError('A selected producer must produce the corresponding resource.');producerChoices[id]=type;}
 return {regionId,assetId:a.assetId,mode:a.mode,amount:a.amount,source:a.source,horizonMinutes,choices,producerChoices};
}
export function savePlan(game:Game,c:Corp,a:Dict,now:number){
 const options=validateTarget(game,c,a);if(typeof a.name!=='string'||!a.name.trim()||a.name.trim().length>60)throw new GameError('Plan names must contain 1 to 60 characters.');c.savedPlans??=[];
 let previous:Dict|undefined;if(a.id!==undefined){if(typeof a.id!=='string'||!(previous=c.savedPlans.find(p=>p.id===a.id)))throw new GameError('Saved plan not found.',404);}else if(c.savedPlans.length>=20)throw new GameError('A corporation can save at most 20 plans.');
 const plan={...options,id:previous?.id||randomUUID(),name:a.name.trim(),createdAt:previous?.createdAt??now,updatedAt:now};if(previous)c.savedPlans[c.savedPlans.indexOf(previous)]=plan;else c.savedPlans.push(plan);return plan;
}
export function deletePlan(c:Corp,id:unknown){if(typeof id!=='string'||!c.savedPlans?.some(p=>p.id===id))throw new GameError('Saved plan not found.',404);c.savedPlans=c.savedPlans.filter(p=>p.id!==id);}
function exemplar(type:string,now:number):Facility{return {id:`planned:${type}:${randomUUID()}`,type,level:0,xp:0,nextCycle:now,enabled:true,plus:true,allowPlus:false,installed:[],costPaid:0,materialsPaid:{},builtAt:now};}
function rates(t:ReturnType<typeof flowTotals>,id:string,external:Record<string,number>={}){const capacityOutputPerMinute=(t.output[id]||0)+(external[id]||0),capacityInputPerMinute=t.input[id]||0,sustainableOutputPerMinute=t.sustainableOutput[id]||0,sustainableInputPerMinute=t.sustainableInput[id]||0;return {capacityOutputPerMinute,capacityInputPerMinute,capacityNetPerMinute:capacityOutputPerMinute-capacityInputPerMinute,sustainableOutputPerMinute,sustainableInputPerMinute,sustainableNetPerMinute:sustainableOutputPerMinute-sustainableInputPerMinute};}
export function productionTarget(game:Game,c:Corp,input:Dict,now=c.lastProcessed){
 const o=validateTarget(game,c,input);if(!Number.isSafeInteger(now)||now<0)throw new GameError('Invalid planning timestamp.');const r=game.world.regions.find(r=>r.id===o.regionId)!,h=c.holdings[r.id]!,currentFlows=regionalFlows(c,r),currentTotals=flowTotals(currentFlows),balances=resourceBalances(c,r);
 const stock=h.inventory[o.assetId]||0,missing=o.mode==='stock'?Math.max(0,o.amount-stock):0,targetRate=o.mode==='rate'?o.amount:missing/o.horizonMinutes;
 const projectedCorp:Corp={...c,holdings:{...c.holdings,[r.id]:{...h,facilities:h.facilities.map(f=>({...f,installed:[...f.installed]}))}}},ph=projectedCorp.holdings[r.id]!;
 const added:Record<string,number>={},resumed:Record<string,number>={},relevant=new Set([o.assetId]),chosen=new Map<string,string>(),unresolved=new Set<string>(),blockers:Dict[]=[],warnings=new Set<string>(),external:Record<string,number>={};
 const issue=(code:string,message:string,assetId?:string)=>{if(!blockers.some(b=>b.code===code&&b.assetId===assetId&&b.message===message))blockers.push({code,message,...(assetId?{assetId}:{})});};
 const source=(id:string)=>id===o.assetId?o.source:o.choices[id]||'produce';
 const append=(type:string,n:number)=>{if(ph.facilities.length+n>2000){issue('facility_limit','The target would exceed the regional limit of 2,000 facilities.');return false;}for(let i=0;i<n;i++)ph.facilities.push(exemplar(type,now));added[type]=(added[type]||0)+n;return true;};
 let plannedFlows=currentFlows,totals=currentTotals,passes=0;
 if(targetRate>EPS)for(;passes<160;passes++){
  plannedFlows=regionalFlows(projectedCorp,r);totals=flowTotals(plannedFlows);let changed=false;
  // Existing consumers are counted in totals once; only the target's upstream chain is expanded.
  for(const id of [...relevant])if(source(id)!=='buy')for(const f of plannedFlows)if((f.outputs[id]||0)>EPS)for(const inputId of Object.keys(f.inputs))if(!relevant.has(inputId)){relevant.add(inputId);changed=true;}
  for(const id of [...relevant]){
   const required=(totals.input[id]||0)+(id===o.assetId?targetRate:0),deficit=Math.max(0,required-(totals.output[id]||0));
   if(source(id)==='buy'){external[id]=Math.max(0,required-(totals.sustainableOutput[id]||0));continue;}if(deficit<=EPS||unresolved.has(id))continue;
   const selected=o.producerChoices[id],candidates=[...facilityMap.values()].filter(d=>!selected||d.id===selected).map(d=>{const f=exemplar(d.id,now),flow=facilityFlow(f,projectedCorp,r),paused=ph.facilities.filter(x=>x.type===d.id&&!x.enabled).map(x=>facilityFlow(x,projectedCorp,r));return {d,f,flow,output:Math.max(flow.outputs[id]||0,...paused.map(x=>x.outputs[id]||0)),owned:h.facilities.filter(x=>x.type===d.id).length};}).filter(x=>x.output>EPS).sort((a,b)=>Number(b.owned>0)-Number(a.owned>0)||buildCost(a.d,r)/a.output-buildCost(b.d,r)/b.output||a.d.id.localeCompare(b.d.id));
   const candidate=candidates[0];if(!candidate){issue('no_producer',`No selectable factory currently produces ${title(id)} at a positive expected rate. Research, technology, quality upgrades or manual acquisition may be required.`,id);unresolved.add(id);continue;}
   chosen.set(id,candidate.d.id);let left=deficit;
   for(const f of ph.facilities.filter(f=>f.type===candidate.d.id&&!f.enabled)){const output=facilityFlow(f,projectedCorp,r).outputs[id]||0;if(output<=EPS)continue;f.enabled=true;resumed[f.type]=(resumed[f.type]||0)+1;left-=output;changed=true;if(left<=EPS)break;}
   if(left>EPS){const rate=candidate.flow.outputs[id]||0;if(rate<=EPS){issue('quality_capacity',`New level-zero ${candidate.d.name} facilities cannot produce this quality yet.`,id);unresolved.add(id);}else{const count=Math.ceil((left-EPS)/rate);if(count>2000||!append(candidate.d.id,count)){issue('facility_limit',`More than the available whole-factory capacity is required for ${title(id)}.`,id);unresolved.add(id);}else changed=true;}}
   for(const inputId of Object.keys(candidate.flow.inputs))if(!relevant.has(inputId)){relevant.add(inputId);changed=true;}
   // Recompute after adding each group so a shared upstream producer is never counted twice.
   plannedFlows=regionalFlows(projectedCorp,r);totals=flowTotals(plannedFlows);
  }
  if(!changed)break;
 }
 if(passes===160)issue('dependency_cycle','The bounded chain expansion did not converge; review producer choices or cyclic dependencies.');
 const prerequisites:Dict[]=[],seenPrerequisites=new Set<string>();
 for(let pass=0;pass<12;pass++){let changed=false;for(const type of Object.keys(added)){for(const raw of facilityMap.get(type)!.requires||[]){const scope=raw.startsWith('global:')?'global':'regional',id=raw.replace(/^global:/,''),key=scope+':'+id;if(seenPrerequisites.has(key)||!facilityMap.has(id))continue;seenPrerequisites.add(key);const satisfied=(scope==='global'?Object.values(c.holdings):[h]).some(holding=>holding.facilities.some(f=>f.type===id));const planned=ph.facilities.some(f=>f.type===id);prerequisites.push({facilityId:id,name:facilityMap.get(id)!.name,scope,satisfied,additionalCount:satisfied||planned?0:1});if(!satisfied&&!planned){if(append(id,1))changed=true;else issue('prerequisite_capacity',`No room remains for prerequisite ${facilityMap.get(id)!.name}.`);}}}if(!changed)break;}
 plannedFlows=regionalFlows(projectedCorp,r);totals=flowTotals(plannedFlows);
 for(const id of relevant)if(source(id)==='buy')external[id]=Math.max(0,(totals.input[id]||0)+(id===o.assetId?targetRate:0)-(totals.sustainableOutput[id]||0));
 const projectedTotals=flowTotals(plannedFlows,external),current={...rates(currentTotals,o.assetId),actual:balances.find(b=>b.assetId===o.assetId)?.actual||null},projected={...rates(projectedTotals,o.assetId,external),actual:null};
 const types=new Set([...Object.keys(added),...Object.keys(resumed),...chosen.values(),...plannedFlows.filter(f=>Object.keys(f.outputs).some(id=>relevant.has(id))).map(f=>f.facility.type)]);
 const grouped=(flows:FacilityFlow[],type:string,side:'inputs'|'outputs')=>{const out:Record<string,number>={};for(const f of flows.filter(x=>x.facility.type===type))for(const[id,n]of Object.entries(f[side]))add(out,id,n);return out;};
 let construction=0,requiredLand=0;const materials:Record<string,number>={};
 const facilities=[...types].map(type=>{const d=facilityMap.get(type)!,quantity=added[type]||0;construction+=buildCost(d,r)*quantity;requiredLand+=Number(d.land||1)*quantity;for(const[id,n]of Object.entries(d.materials||{}))add(materials,id,Number(n)*quantity);const own=h.facilities.filter(f=>f.type===type);return {facilityId:type,name:d.name,icon:d.icon,existingCount:own.length,activeCount:own.filter(f=>f.enabled).length,resumeCount:resumed[type]||0,additionalCount:quantity,totalCount:ph.facilities.filter(f=>f.type===type).length,inputsPerMinute:grouped(plannedFlows,type,'inputs'),outputsPerMinute:grouped(plannedFlows,type,'outputs'),buildCost:buildCost(d,r)*quantity,land:Number(d.land||1)*quantity,qualityChance:facilityFlow(exemplar(type,now),projectedCorp,r).chance};});
 const used=h.facilities.reduce((n,f)=>n+Number(facilityMap.get(f.type)?.land||1),0),availableLand=Math.max(0,h.land-used),missingLand=Math.max(0,requiredLand-availableLand);let land=0;
 try{land=missingLand?landCost(h,missingLand,c,r):0;}catch{issue('numeric_limit','Required land exceeds supported economic limits.');land=MAX;}
 const money=(n:number)=>{if(!Number.isSafeInteger(n)||n>MAX){issue('numeric_limit','Planned costs exceed supported economic limits.');return MAX;}return n;};construction=money(construction);const total=money(construction+land);
 const requirements={cash:{construction,land,total,available:c.cash,missing:Math.max(0,total-c.cash),availableForPurchases:Math.max(0,c.cash-total)},land:{required:requiredLand,available:availableLand,missing:missingLand,cost:land},materials:Object.entries(materials).filter(([,n])=>n>0).map(([id,n])=>({assetId:id,name:title(id),required:n,available:h.inventory[id]||0,missing:Math.max(0,n-(h.inventory[id]||0)),locked:h.locks.includes(id)})),prerequisites};
 if(requirements.cash.missing)issue('construction_cash',`Construction and land need ${requirements.cash.missing} more cents.`);for(const m of requirements.materials){if(m.missing)issue('construction_material',`Acquire ${m.missing} ${m.name} for construction.`,m.assetId);if(m.locked)issue('locked_material',`Unlock ${m.name} before construction.`,m.assetId);}if(missingLand)issue('land',`Purchase ${missingLand} more land before construction.`);if(Object.values(resumed).some(Boolean))issue('resume','Resume the listed paused factories to use their capacity.');
 const allowance=Math.max(0,buyingLimit(c,h,r,now)-(h.purchaseDay===Math.floor(now/3600000)?h.npcPurchases.spent||0:0));let remainingAllowance=allowance,cashBudget=requirements.cash.availableForPurchases;
 const purchases=Object.entries(external).filter(([,n])=>n>EPS).sort(([a],[b])=>a.localeCompare(b)).map(([id,perMinute])=>{const asset=assetMap.get(id),npcAvailable=!!asset&&asset.npcBuy!==false,playerTradeAvailable=!!asset&&asset.tradeable!==false,quantity=o.mode==='stock'&&id===o.assetId?missing:Math.ceil(perMinute*60),unitPrice=asset?marketPrice(r,id,'buy',now):0,cost=money(Math.ceil(quantity*unitPrice)),affordableQuantity=npcAvailable?Math.max(0,Math.min(quantity,Math.floor(cashBudget/unitPrice),Math.floor(remainingAllowance/unitPrice))):0;const row={assetId:id,name:title(id),perMinute,quantity,unitPrice,total:cost,allowanceRemaining:remainingAllowance,affordableQuantity,npcAvailable,playerTradeAvailable};remainingAllowance-=affordableQuantity*unitPrice;cashBudget-=affordableQuantity*unitPrice;if(!npcAvailable&&!playerTradeAvailable)issue('unavailable_purchase',`${title(id)} cannot be purchased from NPCs or player offers.`,id);else if(!npcAvailable)issue('player_purchase',`Find a player offer for ${title(id)}; availability and price are not guaranteed.`,id);else if(affordableQuantity<quantity)issue('purchase_budget',`The planned ${title(id)} purchase exceeds available cash or the shared hourly NPC allowance.`,id);return row;});
 if(purchases.length)issue('manual_purchase','Purchases are manual. Projected throughput assumes the listed recurring supply is maintained.');
 if(plannedFlows.some(f=>f.chance>0))warnings.add('Quality output is a statistical expectation. Random outcomes, future XP, input quality and changing regional conditions can change completion time.');
 if(h.retail.length)warnings.add('Retail and manual activity are excluded from flow rates and may consume stock or change capital.');
 if(plannedFlows.some(f=>f.facility.allowPlus))warnings.add('Existing plus-input choices are evaluated from current stock; quality allocation can change as that stock runs out.');
 warnings.add('This is a bounded deterministic plan, not a cheapest-build optimizer. Existing producers are preferred, then construction cash per expected unit. Shared existing consumers reserve supply once.');
 warnings.add('Sustainable rates exclude finite stored inputs and conservatively reserve upstream output against full enabled demand. Unused shares are not optimistically reassigned from blocked factories.');
 warnings.add('Construction materials are listed separately and are not automatically manufactured or purchased. New factories use level zero, current regional technology and ordinary input preference.');
 const eta:Dict={status:'blocked',seconds:null,reasons:[]};if(o.mode==='stock'&&missing===0){eta.status='ready';eta.seconds=0;}else if(o.mode==='stock'&&o.source==='produce'&&current.sustainableNetPerMinute>EPS&&!h.retail.some(row=>row.assetId===o.assetId)){
  const relevantCurrent=currentFlows.filter(f=>Object.keys(f.outputs).some(id=>relevant.has(id))),wait=relevantCurrent.reduce((n,f)=>n+Math.max(0,f.facility.nextCycle-now)/1000,0),seconds=Math.ceil(missing/current.sustainableNetPerMinute*60+wait);
  if(seconds<=365*86400){eta.status='estimate';eta.seconds=seconds;eta.reasons=['Current sustainable net flow, plus one pending cycle wait for each contributing facility. No new construction, purchases, retail, exports or manual spending is assumed.'];}else eta.reasons=['The estimate exceeds the one-year display horizon.'];
 }else eta.reasons=[o.mode==='rate'?'Rate targets describe ongoing throughput; they do not have a completion timer.':o.source==='buy'?'Review and execute the purchase before this stock target can complete.':'Current sustainable net production cannot establish a reliable stockpile completion time. Stored inputs may support temporary production.'];
 if(o.mode==='stock'&&h.locks.includes(o.assetId))warnings.add('The target resource is locked against manual use; automated production still accumulates it.');
 const fatal=new Set(['no_producer','quality_capacity','facility_limit','dependency_cycle','prerequisite_capacity','numeric_limit','unavailable_purchase']);
 if(o.mode==='rate'&&projected.sustainableNetPerMinute+EPS<targetRate)issue('unsustainable','The selected chain cannot sustain the requested net output under the conservative shared-supply model.');
 const ready=o.mode==='stock'?missing===0:current.sustainableNetPerMinute+EPS>=targetRate;
 const status=ready?'ready':blockers.some(b=>fatal.has(b.code)||b.code==='unsustainable')?'blocked':'planned';
 const nodes=new Map<string,Dict>(),edges:Dict[]=[];
 const assetNode=(id:string)=>{if(nodes.has('asset:'+id))return;const b=balances.find(x=>x.assetId===id);nodes.set('asset:'+id,{id:'asset:'+id,kind:'asset',assetId:id,name:title(id),icon:assetMap.get(id)?.icon,stock:id==='cash'?c.cash:h.inventory[id]||0,inputPerMinute:totals.input[id]||0,outputPerMinute:(totals.output[id]||0)+(external[id]||0),netPerMinute:(totals.output[id]||0)+(external[id]||0)-(totals.input[id]||0),actual:b?.actual||null,status:external[id]?'purchase':unresolved.has(id)?'blocked':'planned',actions:assetMap.has(id)?[{label:'Review market',screen:'market',payload:{assetId:id}},{label:'Review inventory',screen:'inventory',payload:{assetId:id}}]:[]});};
 assetNode(o.assetId);for(const f of facilities){const id='facility:'+f.facilityId;nodes.set(id,{...f,id,kind:'facility',ownedCount:f.existingCount,status:f.additionalCount?'planned':f.resumeCount?'paused':'owned',actions:[{label:'Review construction',screen:'facilities',payload:{facilityId:f.facilityId}},{label:'Inspect production',screen:'facilities',payload:{tab:'owned',facilityId:f.facilityId}}]});for(const[assetId,n]of Object.entries(f.inputsPerMinute)){assetNode(assetId);edges.push({id:`input:${assetId}:${f.facilityId}`,from:'asset:'+assetId,to:id,kind:'input',quantityPerCycle:null,perMinute:n});}for(const[assetId,n]of Object.entries(f.outputsPerMinute)){assetNode(assetId);edges.push({id:`output:${f.facilityId}:${assetId}`,from:id,to:'asset:'+assetId,kind:'output',quantityPerCycle:null,perMinute:n,qualityDependent:!!assetMap.get(assetId)?.quality});}}
 for(const f of facilities.filter(f=>f.additionalCount>0)){const d=facilityMap.get(f.facilityId)!,to='facility:'+f.facilityId;for(const[id,n]of Object.entries({...d.materials,cash:buildCost(d,r)})){if(!n)continue;assetNode(id);edges.push({id:`construction:${id}:${f.facilityId}`,from:'asset:'+id,to,kind:'construction',quantityPerCycle:Number(n)*f.additionalCount,perMinute:null});}for(const raw of d.requires||[]){const id=raw.replace(/^global:/,''),p=facilityMap.get(id);if(!p)continue;const key='facility:'+id;if(!nodes.has(key)){const holdings=raw.startsWith('global:')?Object.values(c.holdings):[h],owned=holdings.reduce((n,h)=>n+h.facilities.filter(f=>f.type===id).length,0);nodes.set(key,{id:key,kind:'facility',facilityId:id,name:p.name,icon:p.icon,ownedCount:owned,existingCount:owned,additionalCount:0,resumeCount:0,status:owned?'available-globally':'required',actions:[{label:'Review prerequisite',screen:'facilities',payload:{facilityId:id}}]});}edges.push({id:`prerequisite:${id}:${f.facilityId}`,from:key,to,kind:'construction',quantityPerCycle:1,perMinute:null});}}
 return {version:1,generatedAt:now,revision:game.world.revision,regionId:r.id,target:{...o,name:title(o.assetId),stock,missing,requiredNetPerMinute:targetRate},status,current,projected,facilities,requirements,purchases,blockers,warnings:[...warnings],eta,resourceBalances:balances,graph:{nodes:[...nodes.values()],edges,notices:[...warnings],truncated:passes===160},limits:productionTargetLimits,savedPlans:(c.savedPlans||[]).filter(p=>p.regionId===r.id)};
}
