import { useState } from 'react';
import { ArrowRight, Bell, Check, CircleAlert, TrendingUp } from 'lucide-react';
import { useGame, Panel, Badge, Empty, Action, number, money, list, titleCase, type Data } from './ui';
import { AdviceAction, PinnedGoal } from './Planner';

export function Trend({points,value,label,currency=false}:{points:Data[];value:string;label:string;currency?:boolean}) {
 if(points.length<2)return <div className="trend-empty"><TrendingUp size={24}/><strong>{label}</strong><p>History begins with your recorded activity. A second observation is needed to draw a trend.</p></div>;
 const values=points.map(p=>Number(p[value]||0)),min=Math.min(...values),max=Math.max(...values),range=max-min||1,start=Number(points[0].at),end=Number(points.at(-1)!.at),duration=end-start||1,path=values.map((v,i)=>`${18+(Number(points[i].at)-start)/duration*564},${130-(v-min)/range*104}`).join(' '),format=(v:number)=>currency?money(v):number(v);
 return <div className="trend-chart"><div><strong>{label}</strong><span>{format(values.at(-1)!)} <small>latest</small></span></div><svg viewBox="0 0 600 154" role="img" aria-label={`${label}: ${format(values[0])} to ${format(values.at(-1)!)} over ${points.length} server observations`}><line x1="18" y1="130" x2="582" y2="130"/><line x1="18" y1="26" x2="582" y2="26"/><polyline points={path} fill="none" stroke="currentColor" strokeWidth="3" strokeLinejoin="round"/><circle cx="582" cy={130-(values.at(-1)!-min)/range*104} r="4" fill="currentColor"/></svg><div className="trend-caption"><span>{new Date(start).toLocaleTimeString([],{hour:'2-digit',minute:'2-digit'})} · {format(min)} min</span><span>{new Date(end).toLocaleTimeString([],{hour:'2-digit',minute:'2-digit'})} · {format(max)} max</span></div></div>;
}
export function Onboarding() {const {state}=useGame();const advice=state.onboarding;if(!advice)return null;return <Panel title={advice.stageLabel||'Your next chapter'} subtitle="Guidance adapts as your corporation develops" action={<Badge tone="green">{titleCase(advice.stage)}</Badge>}><div className="onboarding-steps">{list(advice.steps).filter(s=>s.stage===advice.stage||s.id===advice.next?.id).slice(0,5).map(step=><div className={`onboarding-step ${step.done?'complete':''}`} key={step.id}><span>{step.done?<Check size={16}/>:<ArrowRight size={16}/>}</span><div className="grow"><strong>{step.title}</strong><p>{step.description}</p></div>{step.action&&<AdviceAction action={step.action}/>}</div>)}</div></Panel>;}
export function OverviewInsights() {const {state,holding,go,advice}=useGame();const [metric,setMetric]=useState('cash');const blocked=list(holding.facilities).filter(f=>f.enabled&&['starved','capacity'].includes(f.status)),inbox=list(state.inbox).filter(i=>i.status==='pending'),readyResearch=Object.values(state.holdings).flatMap((h:any)=>list(h.research).filter(r=>r.status==='ready')),unread=list(state.notifications).filter(n=>!n.read);return <><div className="two-column"><PinnedGoal plan={advice}/><Panel title="Needs your attention" subtitle="Actionable items in the latest server snapshot"><div className="attention-list">{blocked.length>0&&<button onClick={()=>go('facilities',{tab:'owned',filter:'idle'})}><CircleAlert size={19}/><div><strong>{blocked.length} production lines need attention</strong><small>Missing inputs or resource capacity reached</small></div><ArrowRight size={16}/></button>}{inbox.length>0&&<button onClick={()=>go('logistics')}><Bell size={19}/><div><strong>{inbox.length} deliveries waiting</strong><small>Claim confirmed player goods or cash</small></div><ArrowRight size={16}/></button>}{readyResearch.length>0&&<button onClick={()=>go('research')}><Check size={19}/><div><strong>{readyResearch.length} discoveries ready</strong><small>Receive completed regional research</small></div><ArrowRight size={16}/></button>}{unread.length>0&&<button onClick={()=>go('market',{tab:'insights'})}><Bell size={19}/><div><strong>{unread.length} new notifications</strong><small>Trade fills and other recorded events</small></div><ArrowRight size={16}/></button>}{!blocked.length&&!inbox.length&&!readyResearch.length&&!unread.length&&<Empty icon={Check} title="Everything is in hand">Your current snapshot has no outstanding production or claim alerts.</Empty>}</div></Panel></div><Panel title="Corporation performance" subtitle="Observed history · no estimated or backfilled data" action={<select aria-label="Performance metric" value={metric} onChange={e=>setMetric(e.target.value)}><option value="cash">Cash</option><option value="netWorth">Net worth</option><option value="produced">Lifetime units produced</option><option value="earned">Lifetime earned</option></select>}><Trend points={list(state.history?.corporation)} value={metric} label={titleCase(metric.replace(/([A-Z])/g,' $1'))} currency={metric!=='produced'}/></Panel><Onboarding/></>;}

export function TradeInsights({assetId,onSelect}:{assetId:string;onSelect:(id:string)=>void}) {const {state,content,regionId}=useGame();const watched=state.market?.watchlist||[],points=list(state.history?.prices).filter(p=>p.assetId===assetId&&p.regionId===regionId),asset=list(content.assets).find(a=>a.id===assetId);return <><Panel title="Market watchlist" subtitle="Track regional prices from the moment you start watching"><div className="form-panel"><div className="button-row"><Action type="market.watch" data={{assetId,enabled:!watched.includes(assetId)}} variant="secondary">{watched.includes(assetId)?'Remove from watchlist':'Watch selected resource'}</Action><Badge>{watched.length} / 24 watched</Badge></div><div className="filter-chips">{watched.map((id:string)=><button className={id===assetId?'active':''} key={id} onClick={()=>onSelect(id)}>{list(content.assets).find(a=>a.id===id)?.name||titleCase(id)}</button>)}</div><Trend points={points} value="buy" label={`${asset?.name||titleCase(assetId)} · NPC purchase price`} currency/><Trend points={points} value="sell" label={`${asset?.name||titleCase(assetId)} · NPC sale price`} currency/><p className="muted">Watched prices are sampled hourly. Each chart uses this region’s actual recorded quotes; a flat line means the observed price was unchanged.</p></div></Panel><NotificationCenter/><PersonalTradeHistory/></>;}
export function NotificationCenter() {const {state}=useGame();const notes=list(state.notifications);return <Panel title="Notifications" subtitle="Persistent events recorded for your corporation" action={<Action type="notification.read" data={{all:true}} variant="quiet" disabled={!notes.some(n=>!n.read)}>Mark all read</Action>}><div className="notification-list">{notes.map(note=><div className={`notification-row ${note.read?'read':''}`} key={note.id}><Bell size={18}/><div className="grow"><strong>{note.title}</strong><p>{note.message}</p><small>{new Date(note.at).toLocaleString()}</small></div>{!note.read&&<Action type="notification.read" data={{ids:[note.id]}} variant="quiet">Mark read</Action>}</div>)}</div>{!notes.length&&<Empty icon={Bell} title="You’re all caught up">Player fills and other significant events will be recorded here.</Empty>}</Panel>;}
export function PersonalTradeHistory() {const {state}=useGame();const trades=list(state.trades||state.market?.trades).filter(t=>t.buyerId===state.corporation.id||t.sellerId===state.corporation.id||t.buyer===state.corporation.id||t.seller===state.corporation.id);return <Panel title="Your executed trades" subtitle="Completed player matches and actual fees"><div className="table-scroll"><table><thead><tr><th>Resource</th><th>Side</th><th>Quantity</th><th>Gross value</th><th>Fee paid by seller</th><th>Net sale proceeds</th><th>Executed</th></tr></thead><tbody>{trades.map(t=><tr key={t.id}><td>{titleCase(t.assetId)}</td><td>{t.sellerId===state.corporation.id||t.seller===state.corporation.id?'Sold':'Bought'}</td><td>{number(t.quantity)}</td><td>{money(t.quantity*t.price)}</td><td>{money(t.fee)}</td><td>{t.sellerId===state.corporation.id||t.seller===state.corporation.id?money(t.netProceeds??t.quantity*t.price-t.fee):"—"}</td><td>{new Date(t.at).toLocaleString()}</td></tr>)}</tbody></table></div>{!trades.length&&<Empty icon={TrendingUp} title="No executed player trades yet">Completed matches involving your corporation appear here.</Empty>}</Panel>;}
