import { useEffect, useState } from 'react';
import { ArrowRight, ChevronRight, GitBranch, LockKeyhole, Package, Pin, Search, Settings2, ShieldCheck, Trash2 } from 'lucide-react';
import { Action, Confirm, Empty, EntityIcon, Field, Panel, Quantity, Resources, list, money, number, titleCase, useGame, type Data } from './ui';
import { useViewPreference } from './view-state';
import { Drawer } from './drawer';

const defaultWatch=['wood','energy'];
const duration=(seconds:number|null|undefined)=>seconds==null?'—':seconds<60?'Less than 1 min':seconds<3600?`${number(seconds/60,1)} min`:seconds<86400?`${number(seconds/3600,1)} hr`:`${number(seconds/86400,1)} days`;
const signed=(value:number)=>`${value>0?'+':''}${number(value,2)}`;
function rates(balance:Data|undefined,basis:string){
 if(!balance)return null;
 if(basis==='actual')return balance.actual?{input:balance.actual.inputPerMinute,output:balance.actual.outputPerMinute,net:balance.actual.netPerMinute}:null;
 const prefix=basis==='sustainable'?'sustainable':'capacity';
 return {input:balance[`${prefix}InputPerMinute`],output:balance[`${prefix}OutputPerMinute`],net:balance[`${prefix}NetPerMinute`]};
}

export function ResourceWatchbar(){
 const {holding,content,go}=useGame();const [pinned,setPinned]=useViewPreference<string[]>('resources.pinned',defaultWatch),[open,setOpen]=useState(false),[search,setSearch]=useState('');
 const assets=list(content.assets),balances=list(holding.resourceBalances),valid=pinned.filter(id=>assets.some(a=>a.id===id)).slice(0,6);
 return <><aside className="resource-watchbar" aria-label="Watched production resources">
  <span className="watchbar-label"><Pin size={13}/> Resources</span>
  {valid.map(id=>{const asset=assets.find(a=>a.id===id),balance=balances.find(b=>b.assetId===id);return <button key={id} className="watch-resource" onClick={()=>go('inventory',{assetId:id})} title={`${asset?.name}: expected net production at enabled capacity. Open supply details.`}><EntityIcon entity={asset} size={22}/><span><strong>{number(holding.inventory[id])}</strong><small>{asset?.name}</small></span><span className={(balance?.capacityNetPerMinute||0)<0?'deficit-text':'positive'}>{balance?signed(balance.capacityNetPerMinute)+'/min':'—'}</span></button>;})}
  {!valid.length&&<span className="muted">Pin resources to follow production across screens.</span>}
  <button className="icon-button" aria-label="Customize resource bar" onClick={()=>setOpen(true)}><Settings2 size={16}/></button>
 </aside>{open&&<Drawer title="Your resource bar" onClose={()=>setOpen(false)}><p>Choose up to six resources for this region. Rates show expected net production at enabled capacity.</p><Field label="Find resource to pin"><input value={search} onChange={e=>setSearch(e.target.value)} placeholder="Resource name"/></Field><div className="pin-resource-list">{assets.filter(a=>a.name.toLowerCase().includes(search.toLowerCase())).map(a=><label key={a.id}><input type="checkbox" checked={valid.includes(a.id)} disabled={!valid.includes(a.id)&&valid.length>=6} onChange={e=>setPinned(e.target.checked?[...valid,a.id]:valid.filter(id=>id!==a.id))}/><EntityIcon entity={a} size={24}/><span>{a.name}</span></label>)}</div><button className="button secondary" onClick={()=>setPinned([])}>Clear resource bar</button></Drawer>}</>;
}

export function Inventory(){
 const {content,holding,act,intent,go,regionId,state}=useGame();
 const [search,setSearch]=useViewPreference('inventory.search',''),[showAll,setShowAll]=useViewPreference('inventory.showAll',false),[sort,setSort]=useViewPreference('inventory.sort','name'),[basis,setBasis]=useViewPreference('inventory.basis','capacity');
 const [pinned,setPinned]=useViewPreference<string[]>('resources.pinned',defaultWatch),[selected,setSelected]=useState<Data|null>(null),[qty,setQty]=useState(1),[scrap,setScrap]=useState(false);
 const balances=list(holding.resourceBalances),defs=list(content.assets),balanceFor=(id:string)=>balances.find(b=>b.assetId===id);
 useEffect(()=>{setSelected(null);setQty(1);setScrap(false);if(intent.assetId){const asset=defs.find(a=>a.id===intent.assetId);if(asset)setSelected(asset);}},[intent.nonce,regionId,state.corporation.id]);
 const assets=defs.filter(a=>(showAll||holding.inventory?.[a.id]>0||(balanceFor(a.id)?.capacityInputPerMinute||0)>0||(balanceFor(a.id)?.capacityOutputPerMinute||0)>0)&&`${a.name} ${a.category}`.toLowerCase().includes(search.toLowerCase())).sort((a,b)=>sort==='quantity'?(holding.inventory[b.id]||0)-(holding.inventory[a.id]||0):sort==='value'?(holding.inventory[b.id]||0)*b.price-(holding.inventory[a.id]||0)*a.price:sort==='net'?(rates(balanceFor(a.id),basis)?.net||0)-(rates(balanceFor(b.id),basis)?.net||0):a.name.localeCompare(b.name));
 const selectedBalance=selected?balanceFor(selected.id):undefined;
 return <><div className="toolbar inventory-toolbar"><div className="search"><Search size={17}/><input aria-label="Search inventory" placeholder="Search resources…" value={search} onChange={e=>setSearch(e.target.value)}/></div><div className="inline-form"><label className="checkbox"><input type="checkbox" checked={showAll} onChange={e=>setShowAll(e.target.checked)}/> Show unowned resources</label><select aria-label="Sort inventory" value={sort} onChange={e=>setSort(e.target.value)}><option value="name">Name A–Z</option><option value="quantity">Largest quantity</option><option value="value">Highest value</option><option value="net">Largest deficit first</option></select></div></div>
 <div className="balance-basis"><Field label="Production rate basis"><select value={basis} onChange={e=>setBasis(e.target.value)}><option value="capacity">Expected enabled capacity</option><option value="sustainable">Sustainable supply</option><option value="actual">Recorded production</option></select></Field><p>{basis==='actual'?'Measured production since observation began; a dash means no reliable observation yet. Trading and manual transfers are excluded.':basis==='sustainable'?'Conservative steady output supported by recurring input supply. Finite stock buffers are excluded.':'Expected rates if enabled facilities can keep running. Shared shortages and output capacity can reduce production.'}</p></div>
 <Panel><div className="table-scroll"><table className="resource-balances"><thead><tr><th>Resource</th><th>Stock</th><th>Produced/min</th><th>Consumed/min</th><th>Net/min</th><th>Stock forecast</th><th>Controls</th></tr></thead><tbody>{assets.map(a=>{const balance=balanceFor(a.id),rate=rates(balance,basis);return <tr key={a.id} className={rate&&rate.net<0?'resource-deficit':''}><td><div className="entity-cell"><EntityIcon entity={a} size={30}/><div><strong>{a.name}</strong><small>{money((holding.inventory[a.id]||0)*a.price)} reference value</small></div>{holding.locks?.includes(a.id)&&<LockKeyhole size={13} className="muted"/>}</div></td><td className="number">{number(holding.inventory[a.id])}</td><td className="positive number">{rate?number(rate.output,2):'—'}</td><td className="number">{rate?number(rate.input,2):'—'}</td><td><button className={`balance-link ${rate&&rate.net<0?'deficit-text':'positive'}`} aria-label={`Inspect ${a.name} supply`} onClick={()=>{setSelected(a);setQty(1);}}>{rate?signed(rate.net):'—'}<ChevronRight size={12}/></button></td><td className="forecast-cell">{balance?.depletionSeconds!=null?<><span className="deficit-text">Empty in {duration(balance.depletionSeconds)}</span><small>At expected capacity</small></>:balance?.fullSeconds!=null?<><span>Full in {duration(balance.fullSeconds)}</span><small>At sustainable supply</small></>:<span className="muted">No finite estimate</span>}</td><td><div className="button-row"><button className="icon-button" aria-label={`${pinned.includes(a.id)?'Unpin':'Pin'} ${a.name}`} disabled={!pinned.includes(a.id)&&pinned.length>=6} onClick={()=>setPinned(pinned.includes(a.id)?pinned.filter(id=>id!==a.id):[...pinned,a.id])}><Pin size={15} fill={pinned.includes(a.id)?'currentColor':'none'}/></button><button className="button secondary small" onClick={()=>{setSelected(a);setQty(1);}}>Manage <ChevronRight size={13}/></button></div></td></tr>;})}</tbody></table></div>{!assets.length&&<Empty icon={Package} title="Your shelves are ready">Resources appear when you build production lines or receive supplies.</Empty>}</Panel>
 <div className="info-note"><ShieldCheck size={18}/><p>Rates and stock forecasts come from the server. Forecasts assume unchanged production and no trades or transfers. Locked resources remain available to production but are protected from manual spending.</p></div>
 {selected&&<Confirm title={scrap?`Scrap ${selected.name}?`:selected.name} button={scrap?'Confirm scrap':'Done'} danger={scrap} onClose={()=>{setSelected(null);setScrap(false);}} onConfirm={async()=>{if(scrap){if(await act('inventory.scrap',{assetId:selected.id,quantity:qty})){setSelected(null);setScrap(false);}}else setSelected(null);}}><div className="asset-detail"><EntityIcon entity={selected} size={56}/><div><h3>{number(holding.inventory[selected.id])} in stock</h3><p>{selected.description||titleCase(selected.category)}</p></div></div>{scrap?<p>Scrap {number(qty)} {selected.name}. This permanently consumes these resources and creates scrap for facility XP.</p>:<><Resources items={{[selected.id]:holding.inventory[selected.id]||0}}/>
  <div className="resource-supply-detail"><h3>Supply and demand</h3>{selectedBalance?<><div className="preview-line"><span>Expected net capacity</span><strong className={selectedBalance.capacityNetPerMinute<0?'deficit-text':'positive'}>{signed(selectedBalance.capacityNetPerMinute)}/min</strong></div><div className="preview-line"><span>Sustainable net rate</span><strong>{signed(selectedBalance.sustainableNetPerMinute)}/min</strong></div>{selectedBalance.actual&&<div className="preview-line"><span>Recorded net production</span><strong>{signed(selectedBalance.actual.netPerMinute)}/min</strong></div>}{selectedBalance.warnings?.map((warning:string)=><p className="inline-warning" key={warning}>{warning}</p>)}{(['producers','consumers'] as const).map(kind=><div key={kind}><h4>{titleCase(kind)}</h4>{list(selectedBalance[kind]).map((facility,i)=><button className="supply-participant" key={facility.facilityId||i} onClick={()=>go('facilities',{tab:'owned',facilityId:facility.type})}><span>{facility.name}{facility.count>1?` ×${facility.count}`:''}</span><strong>{number(facility.perMinute,2)}/min</strong><ArrowRight size={13}/></button>)}{!selectedBalance[kind]?.length&&<small className="muted">No enabled {kind} in this region.</small>}</div>)}</>:<p className="muted">No production flow for this resource yet.</p>}<div className="button-row"><button className="button secondary" onClick={()=>go('chains',{assetId:selected.id})}><GitBranch size={15}/> View production chain</button><button className="button secondary" onClick={()=>go('planner',{assetId:selected.id})}>Plan output</button><button className="button secondary" onClick={()=>go('market',{assetId:selected.id,tab:'npc'})}>Trade resource</button></div></div>
  <Action type="inventory.lock" data={{assetId:selected.id}} variant="secondary"><LockKeyhole size={15}/> {holding.locks?.includes(selected.id)?'Unlock resource':'Lock resource'}</Action><hr/><Field label="Quantity to scrap"><Quantity value={qty} onChange={setQty} max={Math.max(1,holding.inventory[selected.id]||1)}/></Field><button className="button danger" disabled={!selected.scrappable||!holding.inventory[selected.id]||holding.locks?.includes(selected.id)} onClick={()=>setScrap(true)}><Trash2 size={15}/> Review scrap</button></>}</Confirm>}
 </>;
}
