import { lazy, Suspense, useEffect, useState } from 'react';
import { ArrowRight, Check, CircleHelp, Flag, GitBranch, Pin, RefreshCw, Save, Target, Trash2 } from 'lucide-react';
import { useGame, Panel, Field, Quantity, EntityIcon, Badge, Empty, Action, money, number, titleCase, list, type Data, type Screen } from './ui';
import { useViewPreference } from './view-state';
const ProductionGraph = lazy(() => import('./ProductionGraph').then(module => ({default:module.ProductionGraph})));
import './planner.css';

export function AdviceAction({action}:{action:Data}) { const {go,act}=useGame();return <button className="button secondary small" onClick={()=>action.actionType?void act(action.actionType,action.payload):go(action.screen as Screen,action.payload)}>{action.label}<ArrowRight size={13}/></button>; }
export function PinnedGoal({plan}:{plan:Data|null}) {const {go}=useGame();const goal=plan?.goal;if(plan?.pinnedGoal?.completed)return <Panel title="Production goal completed" subtitle="Your planned facilities are built" action={<Badge tone="green"><Check size={12}/> COMPLETE</Badge>}><div className="form-panel"><p>{number(plan.pinnedGoal.currentCount)} total {titleCase(plan.pinnedGoal.facilityId)} facilities now stand in this region. Your target was {number(plan.pinnedGoal.targetCount)}.</p><div className="button-row"><button className="button primary" onClick={()=>go('planner')}>Plan another milestone</button><Action type="goal.clear" variant="quiet">Clear completed goal</Action></div></div></Panel>;if(!goal)return <Panel title="Your next milestone" subtitle="Turn a construction bill into a practical plan"><div className="form-panel"><p>Pick a facility to compare capital, land, materials, prerequisites, and your current production.</p><button className="button secondary" onClick={()=>go('planner')}><Flag size={16}/> Choose a production goal</button></div></Panel>;return <Panel title="Pinned production goal" action={<Badge tone={goal.ready?'green':'amber'}>{goal.ready?'READY TO BUILD':'IN PROGRESS'}</Badge>}><div className="form-panel"><div className="entity-cell"><EntityIcon entity={goal} size={48}/><div><h3>{number(goal.quantity)} × {goal.name}</h3><p>{goal.blockers.length?`${goal.blockers.length} requirements still need attention`:'The server confirms the construction requirements are met.'}</p></div></div><p>{goal.eta.status==='estimate'?`Estimated resource wait: ${number(goal.eta.seconds/60,1)} minutes at current rates.`:goal.eta.status==='blocked'?'Manual steps remain; a completion time cannot yet be predicted.':'Ready for your construction confirmation.'}</p><button className="button primary" onClick={()=>go('planner',{facilityId:goal.facilityId,quantity:goal.quantity})}>Open goal plan <ArrowRight size={15}/></button></div></Panel>;}

type TargetSettings = {assetId:string;mode:'rate'|'stock';amount:number;source:'produce'|'buy';horizonMinutes:number;choices:Record<string,'produce'|'buy'>;producerChoices:Record<string,string>};
const defaultTarget:TargetSettings={assetId:'steel',mode:'rate',amount:10,source:'produce',horizonMinutes:60,choices:{},producerChoices:{}};

export function Planner({chains=false}:{chains?:boolean}) {
 const {state,content,regionId,api,intent,go,act,busy}=useGame(), pinned=state.pinnedGoals?.[regionId];
 const [workspace,setWorkspace]=useViewPreference<'target'|'construction'>('planner-workspace','target');
 const [target,setTarget]=useViewPreference<TargetSettings>('planner-target',defaultTarget);
 const [facilityId,setFacilityId]=useState(intent.facilityId||pinned?.facilityId||list(content.facilities)[0]?.id||''),[quantity,setQuantity]=useState(intent.quantity||pinned?.quantity||1);
 const [result,setResult]=useState<{key:string;data:Data}|null>(null),[loading,setLoading]=useState(false),[error,setError]=useState(''),[revision,setRevision]=useState(0);
 const [planName,setPlanName]=useState(''),[savedId,setSavedId]=useState('');
 const savedPlans=list(state.savedPlans).filter(p=>p.regionId===regionId);
 const loadPlan=(saved:Data)=>{setTarget({assetId:saved.assetId,mode:saved.mode,amount:saved.amount,source:saved.source,horizonMinutes:saved.horizonMinutes||60,choices:saved.choices||{},producerChoices:saved.producerChoices||{}});setSavedId(saved.id);setPlanName(saved.name);setWorkspace('target');};
 useEffect(()=>{if(intent.tab==='target'||intent.tab==='construction')setWorkspace(intent.tab);if(intent.facilityId){setFacilityId(intent.facilityId);setWorkspace('construction');}if(intent.quantity)setQuantity(intent.quantity);if(intent.assetId&&!chains){setTarget(previous=>({...previous,assetId:intent.assetId,...(intent.mode?{mode:intent.mode}:{}),...(intent.amount?{amount:Number(intent.amount)}:{}),...(intent.source?{source:intent.source}:{})}));setWorkspace('target');}if(intent.planId){const saved=list(state.savedPlans).find(p=>p.id===intent.planId);if(saved)loadPlan(saved);}},[intent.nonce]);
 useEffect(()=>{setSavedId('');setPlanName('');},[regionId]);
 const isTarget=!chains&&workspace==='target';
 const query=new URLSearchParams({regionId,...(isTarget?{assetId:target.assetId,mode:target.mode,amount:String(target.amount),source:target.source,horizonMinutes:String(target.horizonMinutes),choices:JSON.stringify(target.choices),producerChoices:JSON.stringify(target.producerChoices)}:!chains?{facilityId,quantity:String(quantity)}:{})});
 const requestKey=(isTarget?'/api/production-plan?':'/api/plan?')+query;
 useEffect(()=>{let current=true;setLoading(true);setError('');const timer=window.setTimeout(()=>{api(requestKey).then(data=>{if(current)setResult({key:requestKey,data});}).catch(e=>{if(current)setError(e.message);}).finally(()=>{if(current)setLoading(false);});},180);return()=>{current=false;window.clearTimeout(timer);};},[requestKey,revision,state.revision]);
 const plan=result?.key===requestKey?result.data:null;
 const update=(change:Partial<TargetSettings>)=>setTarget(previous=>({...previous,...change}));
 const performAdvice=(action:Data)=>action.actionType?void act(action.actionType,action.payload):go(action.screen as Screen,action.payload);
 const graphSelection=intent.assetId?`asset:${intent.assetId}`:chains&&intent.facilityId?`facility:${intent.facilityId}`:'';
 const savePlan=async()=>{const response=await act('plan.save',{...(savedId?{id:savedId}:{}),name:planName.trim(),regionId,...target});if(response?.savedPlan)setSavedId(response.savedPlan.id);};
 return <div className="planner-workspace">
 {!chains&&<Panel title="Production workspace" subtitle="Explore a target, compare the required capacity, then decide what to build or buy.">
   <div className="planner-tabs" role="tablist" aria-label="Planner mode"><button role="tab" aria-selected={isTarget} onClick={()=>{setWorkspace('target');go('planner',{tab:'target'});}}><Target size={17}/>Output target</button><button role="tab" aria-selected={!isTarget} onClick={()=>{setWorkspace('construction');go('planner',{tab:'construction'});}}><Flag size={17}/>Construction goal</button></div>
   {isTarget?<><div className="target-form">
    <Field label="Target resource"><select value={target.assetId} onChange={e=>update({assetId:e.target.value})}>{list(content.assets).filter(a=>a.id!=='cash').map(a=><option value={a.id} key={a.id}>{a.name}</option>)}</select></Field>
    <Field label="Target type"><select value={target.mode} onChange={e=>update({mode:e.target.value as 'rate'|'stock',amount:e.target.value==='stock'?Math.max(1,Math.floor(target.amount)):Math.min(1000000,target.amount)})}><option value="rate">Net output per minute</option><option value="stock">Total stockpile</option></select></Field>
    <Field label={target.mode==='rate'?'Target units per minute':'Target stock units'} hint={target.mode==='rate'?'After current regional demand':'Includes stock already held'}><input type="number" min={target.mode==='rate'?.000001:1} max={target.mode==='rate'?1000000:9000000000000} step={target.mode==='rate'?'any':1} value={target.amount} onChange={e=>update({amount:target.mode==='rate'?Math.max(.000001,Math.min(1000000,Number(e.target.value)||.000001)):Math.max(1,Math.min(9000000000000,Math.floor(Number(e.target.value)||1)))})}/></Field>
    <Field label="Supply strategy"><select value={target.source} onChange={e=>update({source:e.target.value as 'produce'|'buy'})}><option value="produce">Produce in this region</option><option value="buy">Buy the target resource</option></select></Field>
    {target.mode==='stock'&&<Field label="Collection horizon (minutes)" hint="Capacity needed to close the stock gap"><input type="number" min={1} max={10080} value={target.horizonMinutes} onChange={e=>update({horizonMinutes:Math.max(1,Math.min(10080,Number(e.target.value)||1))})}/></Field>}
   </div><div className="saved-plan-bar">
    <Field label="Saved production plans"><select value={savedId} onChange={e=>{const saved=savedPlans.find(p=>p.id===e.target.value);if(saved)loadPlan(saved);else{setSavedId('');setPlanName('');}}}><option value="">Unsaved scenario</option>{savedPlans.map(p=><option key={p.id} value={p.id}>{p.name}</option>)}</select></Field>
    <Field label="Plan name"><input maxLength={60} value={planName} onChange={e=>setPlanName(e.target.value)} placeholder="e.g. Steel expansion"/></Field>
    <button className="button secondary" disabled={busy||!planName.trim()} onClick={()=>void savePlan()}><Save size={15}/>{savedId?'Update saved plan':'Save plan'}</button>
    {savedId&&<><button className="button quiet" onClick={()=>{setSavedId('');setPlanName('');}}>Save as new</button><Action type="plan.delete" data={{id:savedId}} variant="quiet" onDone={()=>{setSavedId('');setPlanName('');}}><Trash2 size={15}/>Delete plan</Action></>}
   </div></>:<div className="planner-form"><Field label="Goal facility"><select value={facilityId} onChange={event=>setFacilityId(event.target.value)}>{list(content.facilities).map(f=><option value={f.id} key={f.id}>{f.name}</option>)}</select></Field><Field label="Goal quantity"><Quantity value={quantity} onChange={setQuantity} max={100}/></Field><Action type="goal.pin" data={{facilityId,quantity}}><Pin size={15}/>Pin goal to overview</Action>{pinned&&<Action type="goal.clear" variant="quiet">Clear pinned goal</Action>}</div>}
 </Panel>}
 {error&&<div className="planner-error" role="alert"><strong>Could not calculate this plan</strong><p>{error}</p><button className="button secondary" onClick={()=>setRevision(n=>n+1)}>Retry calculation</button></div>}
 {loading&&!plan?<Empty icon={RefreshCw} title="Calculating your production plan"/>:plan&&<>
 {isTarget?<TargetSummary plan={plan}/>:!chains&&plan.goal&&<ConstructionSummary goal={plan.goal}/>}
 <Panel title={isTarget?'Planned production flow':'Live production network'} subtitle={isTarget?'A server-calculated scenario. Saving or inspecting a plan does not spend resources.':'Select a resource or facility to inspect its connections.'} action={<button className="icon-button" aria-label="Refresh production plan" onClick={()=>setRevision(n=>n+1)}><RefreshCw size={16}/></button>}>
  <Suspense fallback={<Empty icon={GitBranch} title="Loading production workspace"/>}><ProductionGraph graph={plan.graph||{nodes:[],edges:[]}} initialSelection={graphSelection} onAction={performAdvice} nodeControls={isTarget?(node)=>{
   if(node.kind!=='asset'||node.assetId==='cash')return null;
   const asset=list(content.assets).find(a=>a.id===node.assetId);const producerOptions=list(content.facilities).filter(f=>Object.hasOwn(f.outputs||{},asset?.baseAsset||node.assetId));
   return <div className="node-strategy"><Field label={`Supply choice for ${node.name}`}><select value={node.assetId===target.assetId?target.source:target.choices[node.assetId]||'produce'} onChange={e=>node.assetId===target.assetId?update({source:e.target.value as 'produce'|'buy'}):update({choices:{...target.choices,[node.assetId]:e.target.value as 'produce'|'buy'}})}><option value="produce">Produce</option><option value="buy">Buy (review live availability)</option></select></Field>{producerOptions.length>1&&<Field label={`Producer for ${node.name}`}><select value={target.producerChoices[node.assetId]||''} onChange={e=>{const choices={...target.producerChoices};if(e.target.value)choices[node.assetId]=e.target.value;else delete choices[node.assetId];update({producerChoices:choices});}}><option value="">Server default producer</option>{producerOptions.map(f=><option value={f.id} key={f.id}>{f.name}</option>)}</select></Field>}</div>;
  }:undefined}/></Suspense>
 </Panel>
 {isTarget?<TargetSummary plan={plan} details/>:<SupplyWarnings graph={plan.graph}/>}
 </>}
 </div>;
}

function TargetSummary({plan,details=false}:{plan:Data;details?:boolean}) {
 const {go}=useGame(),target=plan.target,current=plan.current||{},projected=plan.projected||{},requirements=plan.requirements||{},facilities=list(plan.facilities);
 if(!details)return <>
 <div className="target-status"><div><span className="eyebrow">{target.mode==='rate'?'NET OUTPUT TARGET':'STOCKPILE TARGET'}</span><h2>{number(target.amount,Math.abs(target.amount)<.01?6:2)} {target.name}{target.mode==='rate'?'/min':''}</h2><p>{target.mode==='stock'?`${number(target.stock)} held · ${number(target.missing)} more needed · ${number(target.horizonMinutes)} minute collection horizon.`:'Current regional consumption is included in the server calculation.'}</p></div><Badge tone={plan.status==='ready'?'green':plan.status==='blocked'?'red':'amber'}>{plan.status==='ready'?'TARGET MET':plan.status==='blocked'?'BLOCKED':'ACTION REQUIRED'}</Badge></div>
 <div className="target-metrics"><div><span>Current theoretical net</span><strong>{number(current.capacityNetPerMinute,Math.abs(current.capacityNetPerMinute)<.01?6:2)}<small>/min</small></strong><p>Enabled capacity before input shortages</p></div><div><span>Current sustainable net</span><strong>{number(current.sustainableNetPerMinute,Math.abs(current.sustainableNetPerMinute)<.01?6:2)}<small>/min</small></strong><p>Limited by shared input supply</p></div><div><span>Planned sustainable net</span><strong>{number(projected.sustainableNetPerMinute,Math.abs(projected.sustainableNetPerMinute)<.01?6:2)}<small>/min</small></strong><p>After the displayed changes</p></div><div><span>Construction & land</span><strong>{money(requirements.cash?.total)}</strong><p>Available capital {money(requirements.cash?.available)}</p></div></div>
 <p className="planner-note">{current.actual?`Observed net rate: ${number(current.actual.netPerMinute,Math.abs(current.actual.netPerMinute)<.01?6:2)}/min over the server observation window.`:'Observed actual throughput is not yet available; the rates above are capacity calculations.'} {target.mode==='rate'?'Rate targets describe ongoing throughput and have no completion timer.':plan.eta?.status==='estimate'?`At current sustainable production, the stock target is estimated in ${number(plan.eta.seconds/60,1)} minutes.`:plan.eta?.status==='ready'?'The server confirms this target is already satisfied.':'No completion time is promised until the required supply and manual steps are resolved.'}</p>
 </>;
 return <>
 <Panel title="Capacity to reach this target" subtitle="Whole facilities, shared inputs, and existing regional production are considered together.">
  {facilities.length?<div className="table-scroll"><table className="capacity-table"><thead><tr><th>Facility</th><th>Existing</th><th>Active</th><th>Resume</th><th>Add</th><th>Planned total</th><th>Construction</th><th>Land</th><th>Next step</th></tr></thead><tbody>{facilities.map(f=><tr key={f.facilityId}><td><strong>{f.name}</strong><small>Expected quality chance {number(Number(f.qualityChance||0)*100,1)}%</small></td><td>{number(f.existingCount)}</td><td>{number(f.activeCount)}</td><td>{number(f.resumeCount)}</td><td className={f.additionalCount?'positive':''}>+{number(f.additionalCount)}</td><td>{number(f.totalCount)}</td><td>{money(f.buildCost)}</td><td>{number(f.land)} acres</td><td><button className="button secondary small" onClick={()=>go('facilities',{facilityId:f.facilityId,tab:f.additionalCount?'catalog':'owned'})}>{f.additionalCount?'Review build':'View facilities'}<ArrowRight size={13}/></button></td></tr>)}</tbody></table></div>:<div className="form-panel"><p>No facility capacity changes are included in this scenario.</p></div>}
 </Panel>
 <div className="two-column"><Panel title="Resources & constraints"><div className="form-panel"><div className="preview-line"><span>Additional land / free land</span><strong>{number(requirements.land?.required)} / {number(requirements.land?.available)} acres</strong></div><div className="preview-line"><span>Missing capital</span><strong>{money(requirements.cash?.missing)}</strong></div>{list(requirements.materials).map(m=><div className="preview-line" key={m.assetId}><span>{m.name}{m.locked?' · Locked':''}</span><strong>{number(m.available)} / {number(m.required)}{m.missing?` · ${number(m.missing)} missing`:''}</strong></div>)}{list(requirements.prerequisites).map(p=><div className="preview-line" key={p.facilityId}><span>{p.name} · {p.scope}</span><Badge tone={p.satisfied?'green':'amber'}>{p.satisfied?'AVAILABLE':`${number(p.additionalCount)} required`}</Badge></div>)}<p className="muted">This plan is read-only. Build, resume, purchase, or unlock resources through the normal confirmation screens.</p></div></Panel>
 <Panel title="Feasibility & next steps" subtitle="Current constraints and explicit assumptions"><div className="form-panel">{list(plan.blockers).map((b,i)=><div className="planner-blocker" key={`${b.code}-${i}`}><CircleHelp size={18}/><div><p>{b.message}</p>{b.assetId&&<button className="button secondary small" onClick={()=>go('market',{assetId:b.assetId})}>Review {titleCase(b.assetId)} supply<ArrowRight size={13}/></button>}</div></div>)}{!plan.blockers?.length&&<p className="positive"><Check size={17}/>No unresolved constraint is reported for this scenario.</p>}{plan.warnings?.map((warning:string)=><p className="planner-note" key={warning}>{warning}</p>)}{plan.eta?.reasons?.map((reason:string)=><p className="muted" key={reason}>{reason}</p>)}</div></Panel></div>
 {plan.purchases?.length>0&&<Panel title="Purchases in this scenario" subtitle="Recurring supply and one-time stock purchases use current server quotes, not guaranteed future prices."><div className="table-scroll"><table><thead><tr><th>Resource</th><th>Demand</th><th>Quoted quantity</th><th>Unit quote</th><th>Quoted total</th><th>NPC allowance</th><th>Next step</th></tr></thead><tbody>{plan.purchases.map((p:Data)=><tr key={p.assetId}><td><strong>{p.name}</strong><small>{p.npcAvailable?'NPC supply available':p.playerTradeAvailable?'Player availability requires a matching offer':'No automated supply available'}</small></td><td>{number(p.perMinute,Math.abs(p.perMinute)<.01?6:2)}/min</td><td>{number(p.quantity)}</td><td>{p.npcAvailable?money(p.unitPrice):'Unavailable'}</td><td>{p.npcAvailable?money(p.total):'Unquoted'}</td><td>{money(p.allowanceRemaining)}</td><td><button className="button secondary small" onClick={()=>go('market',{assetId:p.assetId,quantity:p.quantity})}>Review purchase<ArrowRight size={13}/></button></td></tr>)}</tbody></table></div></Panel>}
 </>;
}

function ConstructionSummary({goal}:{goal:Data}) {
 return <><div className="planner-status"><EntityIcon entity={goal} size={52}/><div className="grow"><h2>{number(goal.quantity)} × {goal.name}</h2><p>{goal.eta.status==='ready'?'All requirements met. Review construction when you are ready.':goal.eta.status==='estimate'?`Estimated wait: ${number(goal.eta.seconds/60,1)} minutes at current rates.`:'Manual requirements prevent a reliable completion estimate.'}</p></div><Badge tone={goal.ready?'green':'amber'}>{goal.ready?'READY':'NEEDS ATTENTION'}</Badge></div><div className="two-column"><Panel title="Construction requirements"><div className="form-panel"><div className="preview-line"><span>Construction cash</span><strong>{money(goal.requirements.cash.required)}</strong></div><div className="preview-line"><span>Cash available</span><strong>{money(goal.requirements.cash.available)}</strong></div><div className="preview-line"><span>Required / free land</span><strong>{number(goal.requirements.land.required)} / {number(goal.requirements.land.available)} acres</strong></div>{goal.requirements.land.missing>0&&<div className="preview-line"><span>Additional land cost</span><strong>{money(goal.requirements.land.purchaseCost)}</strong></div>}<div className="requirement-list">{list(goal.requirements.materials).map(m=><div key={m.assetId}><EntityIcon entity={m} size={28}/><div className="grow"><strong>{m.name}{m.locked?' · Locked':''}</strong><small>{number(m.available)} / {number(m.required)} available · net {number(m.netPerMinute,2)}/min</small>{m.npcBuyQuote&&m.missing>0&&<small>NPC quote: {money(m.npcBuyQuote.totalForMissing)} for the shortage · {money(m.npcBuyQuote.allowanceRemaining)} spending allowance left</small>}</div><Badge tone={m.missing||m.locked?'amber':'green'}>{m.locked?'LOCKED':m.missing?`${number(m.missing)} missing`:'MET'}</Badge></div>)}</div>{list(goal.requirements.prerequisites).map(p=><div className="preview-line" key={p.facilityId}><span>{p.name} · {p.scope}</span>{p.satisfied?<Badge tone="green">BUILT</Badge>:<AdviceAction action={p.action}/>}</div>)}<div className="button-row">{list(goal.actions).map((a,i)=><AdviceAction action={a} key={i}/>)}</div></div></Panel><Panel title="A practical path forward" subtitle={`${goal.blockers.length} outstanding requirements`}><div className="form-panel">{goal.blockers.length?goal.blockers.map((b:Data,i:number)=><div className="planner-blocker" key={i}><CircleHelp size={18}/><div><p>{b.message}</p>{b.action&&<AdviceAction action={b.action}/>}</div></div>):<p className="positive"><Check size={17}/>Your goal is ready to build.</p>}{list(goal.missingFactories).map(f=><div className="planner-blocker" key={f.facilityId}><GitBranch size={18}/><div><p>{f.name} can supply {f.forAssets.map(titleCase).join(', ')}{f.alternative?' (alternative producer)':''}.</p><AdviceAction action={f.action}/></div></div>)}{goal.eta.reasons?.map((reason:string)=><p className="muted" key={reason}>{reason}</p>)}</div></Panel></div></>;
}

function SupplyWarnings({graph}:{graph:Data}) {
 return <Panel title="Bottlenecks and supply warnings" subtitle="Actual stock, upcoming input requirements, and effective rates"><div className="form-panel">{list(graph?.shortages).map(s=><div className="shortage-row" key={s.assetId}><div className="grow"><h3>{s.name}</h3><p>{number(s.stock)} in stock · {number(s.requiredForNextCycles)} required for upcoming cycles · {number(s.netPerMinute,2)} net/min</p>{s.depletionSeconds!==null&&<p>Estimated stock depletion: {number(s.depletionSeconds/60,1)} minutes at current rates.</p>}{s.reasons?.map((r:string)=><small className="block muted" key={r}>{r}</small>)}</div><div className="button-row">{s.actions?.map((a:Data,i:number)=><AdviceAction key={i} action={a}/>)}</div></div>)}{!graph?.shortages?.length&&<p className="positive"><Check size={17}/>No supply shortage detected in this snapshot.</p>}{graph?.notices?.map((notice:string)=><p className="muted" key={notice}>{notice}</p>)}</div></Panel>;
}
